### ISSUE TITLE
Danalock Door Lock supported?

### ISSUE THREAD

**Issue by DJay1** [SphtKr/homebridge-zway#1]
First thanks for your work. Don't want to bother but I'm new to this.
Does homebridge-zway support Door Locks like my Danalock so I can open/close the Lock with Siri?
I use the Device already as a Lock on My Razberry Z-Wave.me.
Thanks in advance for your help and reply.

**Comment by SphtKr** [comment]
Not yet, though I'd love to! Can you send me the contents of `http://your.pi.i.p:8083/ZAutomation/api/v1/devices`? You'll need to login to the Z-Wave standard UI, and then hit that URL (replacing `your.pi.i.p` with your device's IP address of course), and attach or post the contents here.

Since I don't have the device, I'll have to engage in some guesswork. But it should be possible to get basic functionality done "blind". I can send you a pre-release copy of the module for you to install and try to see if it works. Will probably take me a little time though.

**Comment by DJay1** [comment]
Here you go. As mentioned I'm new to this so maybe I will have some more questions from time to time. But would be great to work some things out together.
[Devices.txt](https://github.com/SphtKr/homebridge-zway/files/76744/Devices.txt)

**Comment by SphtKr** [comment]
That's perfect--I see it's pretty much one device and a battery--that will make things quite easy, actually.

Unrelated to your Danalock--are you using the "Trap Events" app? Or what's your device #5? I've got a few remote switches but I haven't managed to get them to show up as a `buttonControl`, but you have...

**Comment by DJay1** [comment]
Device 5 is a door/window sensor.
Device Id	5
Device Name	Türsensor
Device type Routing Binary Sensor
Interview-Status	
Interview complete
+ +++ ++++++
Wireless Activity deep sleep
Application version	32.20
SDK version 4.55.00
Command Class	
Basic, SensorBinary, Alarm, ManufacturerSpecific, Battery, Wakeup, Association, Version,

**Comment by SphtKr** [comment]
Okay, I've taken a quick stab at it. I can't test, but at least it compiles/installes and Homebridge will run with it.

Go here:

https://github.com/SphtKr/homebridge-zway/tree/feature-doorlock

Either clone that branch with git using the URL provided there, or use the "Download ZIP" button. Once you get a copy of the repo, cd into it and type `npm install -g`. That should install the prerelease version of the plugin. Then see if your doorlock shows up in a HomeKit app (I like Eve) and perhaps if Siri will let you say "Open the Danalock" or "Open the door".

For simplicity, I've implemented it as a "Door", rather than a "Lock". Might be able to do the latter afterwards. But for this reason the verbs you'd use with Siri will be "open" or "close" instead of "lock" or "unlock".

**Comment by DJay1** [comment]
Thanks.. the installation worked.. though I alway have to use sudo npm install --unsafe-perm -g to have all rights. Don't know why but this is the only way I know and it works. ;)

So I did this and of course added the platform to my config.json

Reboot the PI and checked Terminal homebridge

Looks good I think..

Loaded plugin: homebridge-harmonyhub
Registering platform 'homebridge-harmonyhub.HarmonyHub'
---
Loaded plugin: homebridge-http
Registering accessory 'homebridge-httpstatus.Http'
---
Loaded plugin: homebridge-netatmo
Registering platform 'homebridge-netatmo.netatmo'
---
Loaded plugin: homebridge-ssh
Registering accessory 'homebridge-ssh.SSH'
---
Loaded plugin: homebridge-wemo
Registering accessory 'homebridge-wemo.WeMo'
---
Loaded plugin: homebridge-zway
Registering accessory 'homebridge-zway.ZWayServer'
Registering platform 'homebridge-zway.ZWayServer'
---
Loaded config.json with 4 accessories and 3 platforms.
---
Loading 3 platforms...
[Harmony Hub Wohnzimmer] Initializing HarmonyHub platform...
[Harmony Hub Wohnzimmer] Searching for Logitech Harmony remote hubs...
Initializing ZWayServer platform...
[netatmo weather] Initializing netatmo platform...
Loading 4 accessories...
[Hombot] Initializing Http accessory...
[Waschtrockner] Initializing WeMo accessory...
[Waschtrockner] Searching for WeMo device with exact name 'Waschtrockner'...
[Spülmaschine] Initializing WeMo accessory...
[Spülmaschine] Searching for WeMo device with exact name 'Spuelmaschine'...
[iTunes Music] Initializing SSH accessory...
[Waschtrockner] Found 'Waschtrockner' device at 10.0.1.5
[Waschtrockner] Found 'Waschtrockner' device at 10.0.1.5
[Spülmaschine] Found 'Spuelmaschine' device at 10.0.1.6
[Spülmaschine] Found 'Spuelmaschine' device at 10.0.1.6
[Harmony Hub Wohnzimmer] Found Logitech Harmony remote hub: 10.0.1.9
[Harmony Hub Wohnzimmer] Connecting to Logitech Harmony remote hub...
Initializing platform accessory 'Hombot'...
Initializing platform accessory 'Danalock'...
.....
...
.

In my iOS Eve App and alternatively the iOS Home App only one Device showed up. The Hombot als a new Device vom Z-Wave.me. This device Is a HTTP_Device_switchBinary_11 
So this means Homebridge is connecting to Z-Wave.me but the Danalock Device is not showing up although it's to see above in the Terminal with "Initializing platform accessory 'Danalock'.

![img_0085](https://cloud.githubusercontent.com/assets/3874239/12128983/0f34e12a-b401-11e5-99ab-24c4a0a8b684.PNG)

**Comment by SphtKr** [comment]
Hmm...well, something went wrong. Can you launch Homebridge with a debug flag for my module, like so:

    DEBUG=ZWayServer home bridge

**Comment by DJay1** [comment]
DEBUG 
[DEBUG.txt](https://github.com/SphtKr/homebridge-zway/files/79752/DEBUG.txt)

**Comment by SphtKr** [comment]
Aw, shoot. Well, your debug output was perfect, I kind of took a bad approach to this. Working up another try.

**Comment by SphtKr** [comment]
Meanwhile, could you get another copy of your `devices` output while your Danalock is locked? It was unlocked last time, and I'm not sure what the closed value looks like. If there's any other state you're aware of (like if it gets stuck, or while it's closing), if you can send me a copy while it's in that state too that would be great--but I know that may be difficult.

**Comment by DJay1** [comment]
Here you go. 
Sometimes Z-Wave.me does not show the status closes although it is closed.
So I send you two debug files one closed_unknown and one definitely closed.
Don't know If there is a difference.
With the Danalock there are only these two states Open and Closed.

[DEBUG_closed_but_unknown.txt](https://github.com/SphtKr/homebridge-zway/files/82664/DEBUG_closed_but_unknown.txt)
[DEBUG_closed.txt](https://github.com/SphtKr/homebridge-zway/files/82665/DEBUG_closed.txt)

**Comment by SphtKr** [comment]
Oh...sorry, I was unclear--I mean the output from `http://your.pi.i.p:8083/ZAutomation/api/v1/devices`, my first request, up at the top of the issue. I hope to see what Z-Wave reports as its status internally. Sorry again. Making good progress here though, I think.

**Comment by SphtKr** [comment]
Okay, I tried a different strategy. This time [go here](https://github.com/SphtKr/homebridge-zway/tree/feature-doorlock-take2), either clone the branch with git using the URL provided there, or use the "Download ZIP" button. Once you get a copy of the repo, cd into it and type `npm install -g`.

See if that works better. I basically started over, so I can't promise this one will work any better. But, this time it should show up as a Lock, not as a Door. So, you probably would say "Hey Siri, *unlock* the Danalock", for instance.

**Comment by DJay1** [comment]
Hey.. yeah.. I works. At least a very big step closer. ;) Thx.
Danalock now shows up as a Lock. I can open and close by Siri. Only by Siri I created a scene that is doing this. In the App (Eve) the State is unfortunately always unknown. So switching there "ungesichert" open or "gesichert" close does not work.

[Output_closed.txt](https://github.com/SphtKr/homebridge-zway/files/83632/Output_closed.txt)
[Output_open.txt](https://github.com/SphtKr/homebridge-zway/files/83633/Output_open.txt)

![img_0106](https://cloud.githubusercontent.com/assets/3874239/12215775/1f1d5cee-b6cb-11e5-9e43-ed946e00b670.PNG)
![img_0105](https://cloud.githubusercontent.com/assets/3874239/12215774/1f1c0e8e-b6cb-11e5-9e6e-5155c0759242.PNG)

**Comment by SphtKr** [comment]
Hmm. Well, I had at least one thing wrong, which was the value for "closed"--it's "close" instead. Update from the new branch again, and at least see if it's any different now. I *think* it should be all correct now, but last time it shouldn't have been showing "Unknown" when it was *unlocked*, only when it was *locked*.

**Comment by DJay1** [comment]
Great. Now the "unknown" status is gone. It says "Gesichert" for open and "Ungesichert" for close.
One thing I notice is that the state changes sometimes slow and sometime not at all in the Z-Wave.me .
Then of course the whole thing is not showing right. But thats nothing we.. I mean you can change. ;)

But maybe there is another small glitch. Z-Wave shows correct that the Lock is closed.
Also in the Eve app the status is "Gesichert" = close.
But the button "Ungesichert" is highlighted in the App. But it should be "Gesichert" highlighted instead.
So now I first have to press "Gesichert" again, sometimes twice until it is highlighted, though it is already close and then press "Ungesichert" that I can open the Lock.

All in all I thing your work is near perfect then. But the Z-Wave.me status from their site is a bit unreliable.

![img_0109](https://cloud.githubusercontent.com/assets/3874239/12217459/6c8c55e4-b701-11e5-969c-bb50f918d11b.PNG)
