### ISSUE TITLE
Schlage Connect Manual Lock/Unlock Status 

### ISSUE THREAD

**Issue by jpaquino3** [SphtKr/homebridge-zway#108]
I have a Schlage Connect lock that works great using Siri or the Home app but fails to update the current lock status when manually locking or unlocking using the keypad or turn knob. Anyone else having an issue like this and is there a remedy? Thank you!

**Comment by ToddGreenfield** [comment]
I have the same issue. From my troubleshooting at least, it isn't a homebridge-zway plugin issue though, rather a zwave problem - see https://github.com/Z-Wave-Me/home-automation/issues/433 - feel free to chime in there. I hadnt heard back from PoltoS as this was a bit more involved than I was comfortable with making changes/modifications. I also have https://github.com/Z-Wave-Me/ExpertUI/issues/251 open, possibly related.

**Comment by gijoecool** [comment]
What version of Z-Way are you running? I can confirm [jensmoes/Niffler](https://github.com/jensmoes/Niffler) works well with Z-Way v2.2.5.

**Comment by jpaquino3** [comment]
Im not home right now to check but I think I'm running the latest version. Does it work well with that?

**Comment by gijoecool** [comment]
It seems like it doesn't work on v2.3, but maybe it works on v2.3.1.

**Comment by ToddGreenfield** [comment]
I am running FW 2.3.1 with UI 1.7.0-RC-9.  I do not think that it is a question of Niffler grabbing the status, it is that the status is not even readable by zway. Zway receives the "event" (which is an Alarm event actually) when manual operation happens (or even the auto-lock if using that function), but zway is listening for door lock events - so zway isn't listening... 

Another challenge with using Niffler (if it worked on this FW), and in my case at least, is that I use the Auto-lock function (the door locks itself automatically after 1-2 minutes), so Niffler would need to Niff way too often, possibly flooding the network.  I actually use the built-in zway app for Peridic Switch Polling, and even though that doesnt poll switches, it works well for everything else.

I am interested to know if anyone has a Schlage Connect and the manual open/close and auto-lock is detected by zway.

**Comment by gijoecool** [comment]
@ToddGreenfield, I think you don't understand how Niffler works. It injects itself and reads the messages Z-Way is already receiving (and only THEN queries for changes). If you see the messages in the logs, then Niffler should be able to read them. Maybe something changed and Niffler no longer works with v2.3.x?

I have it working with manual lock/unlock, I don't know about auto-lock because I don't have that turned on. I am on v2.2.5 though, so maybe this is of no use to you.

**Comment by ToddGreenfield** [comment]
@gijoecool If you review the thread above and reference the #433 issue from zwave/home-automation it also mentions niffler not working in 2.3+. I get how Niffler works, but as you noted, it reads the zway messages in the logfile - which i think is the problem in that zway itself doesn't seem to be seeing those log entries so it's working properly with this specific lock for manual ops.

What specific type of lock do you have? Mine is Schlage Connect model BE469NX with FW Ver MAIN_7.1 - running with Razberry z-way (ZW0500)... Honestly I do not recall if the manual operations worked in zway versions prior to 2.3 (I wasnt paying attention back then), but I was using Niffler before it broke in this version.

**Comment by gijoecool** [comment]
@ToddGreenfield In #433 I only see that Niffler is not working with 2.3, I see no mention of 2.3.1. In your issue #251 I see that you're running 2.3.1 and the UI is not updating. On the [z-wave.me forum](http://forum.zwave.me/viewtopic.php?f=3419&t=24787&p=68646&hilit=niffler&sid=ea37ad10c40265e202929d9206cef668#p68646), it seems that Niffler is working under 2.3.1 for at least one person who is also using it for a lock.

The lock I have is a Schlage BE469NX also, but the firmware is MAIN_6.8. I am using the original RaZberry (ZW0301).

Let me know if there is any other information that I can provide to help.

**Comment by jpaquino3** [comment]
Sorry for the delay in response. I am using version 2.3.1 so I'm guessing Niffler may be an option for me? If anyone can provide information on setting that up, it would be much appreciated. I'm running on on Jessie and cannot seem to find the folders "automation/modules or userModules" to place Niffler in. Thank you for your help so far.

**Comment by gijoecool** [comment]
@jpaquino3 It would be interesting to see if it works on your v2.3.1 installation...

I have copied the four files from [here](https://github.com/jensmoes/Niffler) to /opt/z-way-server/automation/userModules/Niffler. FYI I am using a Raspberry Pi 3 running Jessie. You probably need to restart after copying Niffler, then you should be able to configure Niffler to listen for alarms/events.

**Comment by jpaquino3** [comment]
@gijoecool Works perfectly via keypad and turn knob! Thanks everyone!

**Comment by kpanchen** [comment]
Wonder if anybody has any updates on the issue and how to fix it? Thanks
