### ISSUE TITLE
Homebridge exits with success while starting up

### ISSUE THREAD

**Issue by tieniber** [SphtKr/homebridge-zway#14]
I'm sure this is something I mis-configured, but I can't find any useful errors. I'm trying to run homebridge alongside zway server on a raspberry pi. Ultimately, I'll probably run them on separate pi's, bit I'd really like to get things working first.

When I start up homebridge, I get the following output. Homebridge seems to exit right after initializing the zway plugin, without doing anything else:

    *** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
    *** WARNING *** Please fix your application to use the native API of Avahi!
    *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
    *** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
    *** WARNING *** Please fix your application to use the native API of Avahi!
    *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
    Loaded plugin: homebridge-zway
    Registering accessory 'homebridge-zway.ZWayServer'
    Registering platform 'homebridge-zway.ZWayServer'
    ---
    Loaded config.json with 0 accessories and 1 platforms.
    ---
    Loading 1 platforms...
    Initializing ZWayServer platform...

I don't have any accessories in my config.json file. I think that's correct as the plugin should search my zway server, right? Here's my config file:

    {
        "bridge": {
            "name": "Homebridge",
            "username": "CC:22:3D:E3:CE:31",
            "port": 51826,
            "pin": "004-19-198"
        },

        "description": "This is Eric's config file.",

        "platforms": [
            {
                "platform": "ZWayServer",
                "url": "http://192.168.1.118:8083/",
                "login": "myuser",
                "password": "mypassword"
            }
        ]
    }

Running with the -D or --debug flag doesn't get my any additional output. Any ideas?

**Comment by johannrichard** [comment]
What output do you get if you start homebridge as follows?

`DEBUG=* homebridge -U [path to your homebridge config dir]`

**Comment by tieniber** [comment]
Ok, so I get the following additional output:

      ZWayServer Fetching Z-Way devices... +0ms
      ZWayServer ERROR: Request failed! +718ms
      ZWayServer Error: Parse Error
        at Error (native)
        at Socket.socketOnData (_http_client.js:315:20)
        at emitOne (events.js:90:13)
        at Socket.emit (events.js:182:7)
        at readableAddChunk (_stream_readable.js:147:16)
        at Socket.Readable.push (_stream_readable.js:111:10)
        at TCP.onread (net.js:525:20) +21ms

If I change my url in config.json, I get different results, so it looks like I am hitting the right URL. I'm also able to authenticate at "/ZAutomation/api/v1/login" using postman on my PC and curl on the Pi.

**Comment by Fingerz** [comment]
Why not use the loop back address (127.0.0.1) rather than the assigned IP address if you have them running on the same device...that will avoid any IP address related errors. That's what I'm doing on a Raspberry Pi 2 with 40+ Z-Wave devices and it works quite reliably.

On Feb 21, 2016, at 4:54 AM, tieniber <notifications@github.com> wrote:

Ok, so I get the following additional output:

  ZWayServer Fetching Z-Way devices... +0ms
  ZWayServer ERROR: Request failed! +718ms
  ZWayServer Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:315:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:525:20) +21ms
If I change my url in config.json, I get different results, so it looks like I am hitting the right URL. I'm also able to authenticate at "/ZAutomation/api/v1/login" using postman on my PC and curl on the Pi.

**Comment by tieniber** [comment]
I found the issue, it's a problem on the zway side and caused by the HTTP headers returned, and a security vulnerability that was closed in Node 5.6 and 4.3

Relevant StackOverflow thread [here](http://stackoverflow.com/questions/35525715/http-get-parse-error-code-hpe-unexpected-content-length)

**Comment by SphtKr** [comment]
Hmm.. That's unfortunate. So, for now, this won't work on Node 5.6+ or 4.3+. Noted.

**Comment by SphtKr** [comment]
That issue has been closed as a duplicate, now it's Z-Wave-Me/z-way-issues#102

This just bit me and I'm not finding an easy way to downgrade :scream: going to have to find a workaround... @tieniber did you downgrade node to fix? I'm installing node via homebrew.

**Comment by tieniber** [comment]
I did downgrade Node to 5.5 and it's working. I'm running on a raspberry pi and had just gotten started, so I actually wiped and started over. I tried to downgrade first but I messed up a bunch of dependencies and gave up.

**Comment by SphtKr** [comment]
Yeah, I hit that when I switched to 4.x-LTS, had to `npm uninstall -g homebridge` and then reinstall, that fixed the dependencies problems.

**Comment by aivs** [comment]
I use nodejs 5.7.1 on ArchLinux
```
[root@ArchServer ~]# node -v
v5.7.1
```
my json.config
```
[root@ArchServer ~]# cat .homebridge/json.config 
"platforms": [
    {
        "platform": "ZWayServer",
        "url": "http://192.168.1.108:8083/",
        "login": "admin",
        "password": "qwertyuiop"
    }
]
```
And I cant see that homebridge connected to Z-Way, what the problem?
```
[root@ArchServer ~]# DEBUG=* homebridge -U ~/.homebridge/
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Loaded plugin: homebridge--log
3/6/2016, 7:56:35 PM > ---
3/6/2016, 7:56:36 PM > Loaded plugin: homebridge-zway
3/6/2016, 7:56:36 PM > Registering accessory 'homebridge-zway.ZWayServer'
3/6/2016, 7:56:36 PM > Registering platform 'homebridge-zway.ZWayServer'
3/6/2016, 7:56:36 PM > ---
3/6/2016, 7:56:36 PM > Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
3/6/2016, 7:56:36 PM >                        
3/6/2016, 7:56:36 PM >     ┌────────────┐     
3/6/2016, 7:56:36 PM >     │ 031-45-154 │     
3/6/2016, 7:56:36 PM >     └────────────┘     
3/6/2016, 7:56:36 PM >                        
3/6/2016, 7:56:36 PM > Homebridge is running on port 51826.
  EventedHTTPServer Server listening on port 51826 +0ms
  EventedHTTPServer [::ffff:192.168.1.217] New connection from client +1s
  EventedHTTPServer [::ffff:192.168.1.217] HTTP server listening on port 47298 +4ms
  EventedHTTPServer [::ffff:192.168.1.217] HTTP request: /pair-verify +26ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +11ms
  EventedHTTPServer [::ffff:192.168.1.217] HTTP Response is finished +38ms
  EventedHTTPServer [::ffff:192.168.1.217] HTTP request: /pair-verify +66ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +0ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +3ms
  HAPServer [CC:22:3D:E3:CE:30] Client 730503EC-3BD8-43E0-B861-B3B916C722DB verification complete +6ms
  EventedHTTPServer [::ffff:192.168.1.217] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.1.217] HTTP request: /accessories +12ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:192.168.1.217] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:192.168.1.217] HTTP request: /characteristics +62ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge] Processing characteristic set: [{"aid":1,"iid":8,"ev":true},{"aid":1,"iid":9,"ev":true},{"aid":1,"iid":10,"ev":true}] +2ms
  Accessory [Homebridge] Registering Characteristic "State" for events +2ms
  Accessory [Homebridge] Registering Characteristic "Version" for events +1ms
  Accessory [Homebridge] Registering Characteristic "Control Point" for events +0ms
  EventedHTTPServer [::ffff:192.168.1.217] HTTP Response is finished +0ms
```

**Comment by SphtKr** [comment]
@aivs: well, there are a couple of things to straighten out here first I think. 1: it's supposed to be `config.json` not `json.config`, and the contents you're showing aren't valid. The `"platforms"` key belongs inside a JSON object and you're missing some other parts. Take a look at the Homebridge docs for the full config syntax, if you are still stuck I can help more when I'm not on my phone. 

However, I am guessing that it may not work for you on node 5.7.1 because of the security fix in node that this bug discusses. You may need to downgrade to 4.2.x, I don't think anything 4.3 or greater or 5.x will work right now until Z-Way fixes their non-standard HTTP headers.

**Comment by aivs** [comment]
Config name and content I fixed. I will try with different versions node JS.
What the problem with latest node js? Or may be problem with z-way? If the problem with z-way I can fix it!

**Comment by aivs** [comment]
Now Im use node v4.2.6
my config:
[root@ArchServer ~]# cat .homebridge/json.config 
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
            "accessory": "WeMo",
            "name": "Coffee Maker"
        }
    ],

    "platforms": [
	{
    		"platform": "ZWayServer",
    		"url": "http://192.168.1.108:8083/",
    		"login": "admin",
    		"password": "VssAai01@"
	}    
	]
}
```
[root@ArchServer ~]# DEBUG=* node_modules/homebridge/bin/homebridge -U ~/.homebridge/
```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Loaded plugin: homebridge-zway
Registering accessory 'homebridge-zway.ZWayServer'
Registering platform 'homebridge-zway.ZWayServer'
---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
Homebridge is running on port 51826.
  EventedHTTPServer Server listening on port 51826 +0ms
  EventedHTTPServer [::ffff:192.168.1.217] New connection from client +1s
  EventedHTTPServer [::ffff:192.168.1.217] HTTP server listening on port 50254 +4ms
  EventedHTTPServer [::ffff:192.168.1.217] HTTP request: /pair-verify +23ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 1/2 +10ms
  EventedHTTPServer [::ffff:192.168.1.217] HTTP Response is finished +35ms
  EventedHTTPServer [::ffff:192.168.1.217] HTTP request: /pair-verify +24ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:30] Pair verify step 2/2 +2ms
  HAPServer [CC:22:3D:E3:CE:30] Client 730503EC-3BD8-43E0-B861-B3B916C722DB verification complete +7ms
  EventedHTTPServer [::ffff:192.168.1.217] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.1.217] HTTP request: /accessories +6ms
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: GET /accessories +0ms
  EventedHTTPServer [::ffff:192.168.1.217] HTTP Response is finished +4ms
```

I cant see devices. Can I see error log, why this happens?

**Comment by SphtKr** [comment]
erm...if your `cat` command above is not a typo, you still named it `json.config` instead of `config.json`. It should be `config.json`. The content/format looks right now though :+1:

The issue is over on the Z-Way side, see [this issue](https://github.com/Z-Wave-Me/z-way-issues/issues/102). If you work on that project and can get it corrected, great! It's preventing anyone using Node's http request classes from accessing Z-Way's API.

**Comment by aivs** [comment]
Thanks, with `node v4.2.6`, right `config.json` and recompiled `homebridge` all works fine.
I will check the problem with z-way.

**Comment by SphtKr** [comment]
Closed upstream: https://github.com/Z-Wave-Me/z-way-issues/issues/102 , you must use Z-Way v2.2.2-test-new-webserver though with latest node versions.
