### ISSUE TITLE
Fibaro flood sensor support

### ISSUE THREAD

**Issue by zeair** [SphtKr/homebridge-zway#19]
As discussed on #slack here is my devices output:

{"data":{"structureChanged":true,"updateTime":1458122916,"devices":[{"creationTime":1455192793,"creatorId":8,"deviceType":"battery","h":-592588977,"hasHistory":false,"id":"BatteryPolling_8","location":0,"metrics":{"probeTitle":"Battery","scaleTitle":"%","title":"Battery digest 8","level":100},"permanently_hidden":false,"probeType":"","tags":[],"visibility":true,"updateTime":1458052509},{"creationTime":1455200462,"deviceType":"switchControl","h":-2086613195,"hasHistory":false,"id":"ZWayVDev_zway_Remote_4-0-0-B","location":1,"metrics":{"icon":"","title":"WC Vale","level":"on","change":"downstop"},"permanently_hidden":true,"probeType":"","tags":[],"visibility":true,"updateTime":1458122368},{"creationTime":1455646039,"deviceType":"switchControl","h":-278385034,"hasHistory":false,"id":"ZWayVDev_zway_Remote_21-1-1-B","location":1,"metrics":{"icon":"","title":"WC Flood Seno Fibar Group (21.1.1) Button","level":"off","change":""},"permanently_hidden":true,"probeType":"","tags":[],"visibility":true,"updateTime":1458052509},{"creationTime":1455646049,"deviceType":"switchControl","h":134428102,"hasHistory":false,"id":"ZWayVDev_zway_Remote_21-70-1-B","location":1,"metrics":{"icon":"","title":"WC Flood Seno Fibar Group (21.70.1) Button","level":"off","change":""},"permanently_hidden":true,"probeType":"","tags":[],"visibility":true,"updateTime":1458052509},{"creationTime":1456825418,"deviceType":"switchControl","h":-1134616170,"hasHistory":false,"id":"ZWayVDev_zway_Remote_12-0-0-B","location":1,"metrics":{"icon":"","title":"Bath Cold Water","level":"on","change":"downstop"},"permanently_hidden":false,"probeType":"","tags":[],"visibility":true,"updateTime":1458052509},{"creationTime":1456825580,"deviceType":"switchControl","h":-2022119851,"hasHistory":false,"id":"ZWayVDev_zway_Remote_11-0-0-B","location":1,"metrics":{"icon":"","title":"Bath Hot Water","level":"on","change":""},"permanently_hidden":false,"probeType":"","tags":[],"visibility":true,"updateTime":1458052509},{"creationTime":1457109431,"deviceType":"switchControl","h":-1943137604,"hasHistory":false,"id":"ZWayVDev_zway_Remote_9-1-1-B","location":4,"metrics":{"icon":"","title":"Fibar Group (9.1.1) Button","level":"off","change":""},"permanently_hidden":false,"probeType":"","tags":[],"visibility":true,"updateTime":1458079173},{"creationTime":1457619779,"deviceType":"switchControl","h":609118647,"hasHistory":false,"id":"ZWayVDev_zway_Remote_22-1-1-B","location":1,"metrics":{"icon":"","title":"Fibar Group (22.1.1) Button","level":"on","change":""},"permanently_hidden":false,"probeType":"","tags":[],"visibility":true,"updateTime":1458052509},{"creationTime":1455193924,"creatorId":10,"deviceType":"sensorMultiline","h":-1611286444,"hasHistory":false,"id":"OpenWeather_10","location":0,"metrics":{"scaleTitle":"°C","title":"Szczecin","multilineType":"openWeather","probeTitle":"Temperature","zwaveOpenWeather":{"main":{"temp":277.15,"pressure":1035,"humidity":96,"temp_min":277.15,"temp_max":277.15},"weather":[{"id":800,"main":"Clear","description":"clear sky","icon":"01d"}],"wind":{"speed":3.1,"deg":70}},"level":4,"icon":"http://openweathermap.org/img/w/01d.png","country":"PL","flag":"http://openweathermap.org/images/flags/pl.png"},"permanently_hidden":false,"probeType":"","tags":[],"visibility":true,"updateTime":1458120910},{"creationTime":1455200407,"creatorId":1,"deviceType":"switchBinary","h":1135708217,"hasHistory":false,"id":"ZWayVDev_zway_4-0-37","location":1,"metrics":{"icon":"switch","title":"Toliet water","level":"on"},"permanently_hidden":false,"probeType":"","tags":[],"visibility":true,"updateTime":1458052511},{"creationTime":1455362028,"creatorId":1,"deviceType":"sensorBinary","h":618052632,"hasHistory":false,"id":"ZWayVDev_zway_9-0-48-1","location":4,"metrics":{"probeTitle":"General purpose","scaleTitle":"","icon":"motion","level":"off","title":"Kitchen Flood Sensor Group General purpose (9.0.48.1)"},"permanently_hidden":false,"probeType":"general_purpose","tags":[],"visibility":true,"updateTime":1458122401},{"creationTime":1455362030,"creatorId":1,"deviceType":"sensorBinary","h":1435975678,"hasHistory":false,"id":"ZWayVDev_zway_9-0-156-5-A","location":4,"metrics":{"icon":"alarm","level":"off","title":"Kitchen Flood Sensor Group Water Alarm (9.0.156.5)"},"permanently_hidden":false,"probeType":"alarmSensor_flood","tags":[],"visibility":true,"updateTime":1458079173},{"creationTime":1455362028,"creatorId":1,"deviceType":"sensorMultilevel","h":675311895,"hasHistory":false,"id":"ZWayVDev_zway_9-2-49-1","location":4,"metrics":{"probeTitle":"Temperature","scaleTitle":"°C","level":23.81,"icon":"temperature","title":"Kitchen temperature"},"permanently_hidden":false,"probeType":"temperature","tags":[],"visibility":true,"updateTime":1458079141},{"creationTime":1455362158,"creatorId":1,"deviceType":"switchBinary","h":-1703465105,"hasHistory":false,"id":"ZWayVDev_zway_11-0-37","location":1,"metrics":{"icon":"switch","title":"Bath Hot Water","level":"on"},"permanently_hidden":false,"probeType":"","tags":[],"visibility":true,"updateTime":1458052512},{"creationTime":1455626518,"creatorId":1,"deviceType":"switchBinary","h":-1674835954,"hasHistory":false,"id":"ZWayVDev_zway_12-0-37","location":1,"metrics":{"icon":"switch","title":"Bath Cold Water","level":"on"},"permanently_hidden":false,"probeType":"","tags":[],"visibility":true,"updateTime":1458052512},{"creationTime":1455645971,"creatorId":1,"deviceType":"sensorBinary","h":1840118900,"hasHistory":false,"id":"ZWayVDev_zway_21-0-48-1","location":1,"metrics":{"probeTitle":"General purpose","scaleTitle":"","icon":"motion","level":"off","title":"WC Flood Senor New Fibar Group General purpose (21.0.48.1)"},"permanently_hidden":true,"probeType":"general_purpose","tags":[],"visibility":true,"updateTime":1458122401},{"creationTime":1455645975,"creatorId":1,"deviceType":"sensorBinary","h":-425607331,"hasHistory":false,"id":"ZWayVDev_zway_21-0-156-0-A","location":1,"metrics":{"icon":"alarm","level":"off","title":"WC Flood Senor New Fibar Group General Purpose alarm Alarm (21.0.156.0)"},"permanently_hidden":true,"probeType":"alarmSensor_general_purpose","tags":[],"visibility":true,"updateTime":1458052513},{"creationTime":1455645975,"creatorId":1,"deviceType":"sensorBinary","h":-425602526,"hasHistory":false,"id":"ZWayVDev_zway_21-0-156-5-A","location":1,"metrics":{"icon":"alarm","level":"off","title":"WC Flood Senor New Fibar Group Water Alarm (21.0.156.5)"},"permanently_hidden":false,"probeType":"alarmSensor_flood","tags":[],"visibility":true,"updateTime":1458052513},{"creationTime":1455645972,"creatorId":1,"deviceType":"sensorBinary","h":1868748051,"hasHistory":false,"id":"ZWayVDev_zway_21-1-48-1","location":1,"metrics":{"probeTitle":"General purpose","scaleTitle":"","icon":"motion","level":"off","title":"WC Flood Senor New Fibar Group General purpose (21.1.48.1)"},"permanently_hidden":true,"probeType":"general_purpose","tags":[],"visibility":true,"updateTime":1458122402},{"creationTime":1455645972,"creatorId":1,"deviceType":"sensorMultilevel","h":1897378163,"hasHistory":false,"id":"ZWayVDev_zway_21-2-49-1","location":1,"metrics":{"probeTitle":"Temperature","scaleTitle":"°C","level":25.39,"icon":"temperature","title":"Toilet temperature"},"permanently_hidden":false,"probeType":"temperature","tags":[],"visibility":true,"updateTime":1458122838},{"creationTime":1457619713,"creatorId":1,"deviceType":"sensorBinary","h":-712038061,"hasHistory":false,"id":"ZWayVDev_zway_22-0-48-1","location":1,"metrics":{"probeTitle":"General purpose","scaleTitle":"","icon":"motion","level":"off","title":"Bath flood sensor Group General purpose (22.0.48.1)"},"permanently_hidden":false,"probeType":"general_purpose","tags":[],"visibility":true,"updateTime":1458122402},{"creationTime":1457619715,"creatorId":1,"deviceType":"sensorBinary","h":2072413411,"hasHistory":false,"id":"ZWayVDev_zway_22-0-156-5-A","location":1,"metrics":{"icon":"alarm","level":"off","title":"Bath flood sensor Group Water Alarm (22.0.156.5)"},"permanently_hidden":false,"probeType":"alarmSensor_flood","tags":[],"visibility":true,"updateTime":1458122403},{"creationTime":1457619715,"creatorId":1,"deviceType":"sensorMultilevel","h":-654778798,"hasHistory":false,"id":"ZWayVDev_zway_22-2-49-1","location":1,"metrics":{"probeTitle":"Temperature","scaleTitle":"°C","level":28.76,"icon":"temperature","title":"Bath flood sensor Group Temperature (22.2.49.1)"},"permanently_hidden":false,"probeType":"temperature","tags":[],"visibility":true,"updateTime":1458122403},{"creationTime":1455644497,"creatorId":1,"deviceType":"sensorMultilevel","h":97309529,"hasHistory":false,"id":"ZWayVDev_zway_20-0-49-4","location":4,"metrics":{"probeTitle":"Power","scaleTitle":"W","level":0,"icon":"energy","title":"Fibar Group Power (20.0.49.4)"},"permanently_hidden":false,"probeType":"energy","tags":[],"visibility":true,"updateTime":1458121800},{"creationTime":1455644501,"creatorId":1,"deviceType":"sensorMultilevel","h":97330667,"hasHistory":false,"id":"ZWayVDev_zway_20-0-50-0","location":4,"metrics":{"probeTitle":"Electric","scaleTitle":"kWh","level":5.27,"icon":"meter","title":"Fibar Group Electric Meter (20.0.50.0)"},"permanently_hidden":false,"probeType":"meterElectric_kilowatt_per_hour","tags":[],"visibility":true,"updateTime":1458122403},{"creationTime":1455644501,"creatorId":1,"deviceType":"sensorMultilevel","h":97330669,"hasHistory":false,"id":"ZWayVDev_zway_20-0-50-2","location":4,"metrics":{"probeTitle":"Electric","scaleTitle":"W","level":0,"icon":"meter","title":"Fibar Group Electric Meter (20.0.50.2)"},"permanently_hidden":true,"probeType":"meterElectric_watt","tags":[],"visibility":true,"updateTime":1458122403},{"creationTime":1455644503,"creatorId":1,"deviceType":"sensorBinary","h":-1733485626,"hasHistory":false,"id":"ZWayVDev_zway_20-0-113-4-2-A","location":4,"metrics":{"icon":"alarm","level":"off","title":"Fibar Group Heat Alarm (20.0.113.4.2)"},"permanently_hidden":true,"probeType":"alarm_heat","tags":[],"visibility":true,"updateTime":1458053253},{"creationTime":1455644503,"creatorId":1,"deviceType":"sensorBinary","h":-1729789620,"hasHistory":false,"id":"ZWayVDev_zway_20-0-113-8-4-A","location":4,"metrics":{"icon":"alarm","level":"off","title":"Fibar Group Power Management Alarm (20.0.113.8.4)"},"permanently_hidden":true,"probeType":"alarm_power","tags":[],"visibility":true,"updateTime":1458053253},{"creationTime":1455644503,"creatorId":1,"deviceType":"sensorBinary","h":-1729788659,"hasHistory":false,"id":"ZWayVDev_zway_20-0-113-8-5-A","location":4,"metrics":{"icon":"alarm","level":"off","title":"Fibar Group Power Management Alarm (20.0.113.8.5)"},"permanently_hidden":true,"probeType":"alarm_power","tags":[],"visibility":true,"updateTime":1458053253},{"creationTime":1455644503,"creatorId":1,"deviceType":"sensorBinary","h":-1729787698,"hasHistory":false,"id":"ZWayVDev_zway_20-0-113-8-6-A","location":4,"metrics":{"icon":"alarm","level":"off","title":"Fibar Group Power Management Alarm (20.0.113.8.6)"},"permanently_hidden":true,"probeType":"alarm_power","tags":[],"visibility":true,"updateTime":1458053253},{"creationTime":1455644503,"creatorId":1,"deviceType":"sensorBinary","h":-1729785776,"hasHistory":false,"id":"ZWayVDev_zway_20-0-113-8-8-A","location":4,"metrics":{"icon":"alarm","level":"off","title":"Fibar Group Power Management Alarm (20.0.113.8.8)"},"permanently_hidden":true,"probeType":"alarm_power","tags":[],"visibility":true,"updateTime":1458053253},{"creationTime":1455644503,"creatorId":1,"deviceType":"sensorBinary","h":-1729784815,"hasHistory":false,"id":"ZWayVDev_zway_20-0-113-8-9-A","location":4,"metrics":{"icon":"alarm","level":"off","title":"Fibar Group Power Management Alarm (20.0.113.8.9)"},"permanently_hidden":true,"probeType":"alarm_power","tags":[],"visibility":true,"updateTime":1458053253},{"creationTime":1455644503,"creatorId":1,"deviceType":"sensorBinary","h":-1728868982,"hasHistory":false,"id":"ZWayVDev_zway_20-0-113-9-1-A","location":4,"metrics":{"icon":"alarm","level":"off","title":"Fibar Group System Alarm (20.0.113.9.1)"},"permanently_hidden":true,"probeType":"alarm_system","tags":[],"visibility":true,"updateTime":1458053253},{"creationTime":1455644503,"creatorId":1,"deviceType":"switchMultilevel","h":-844590574,"hasHistory":false,"id":"ZWayVDev_zway_20-0-38","location":4,"metrics":{"icon":"multilevel","title":"Kitchen Light","level":0},"permanently_hidden":false,"probeType":"dimmer","tags":[],"visibility":true,"updateTime":1458080019},{"creationTime":1455905176,"creatorId":1,"deviceType":"switchMultilevel","h":-844560783,"hasHistory":false,"id":"ZWayVDev_zway_20-1-38","location":4,"metrics":{"icon":"multilevel","title":"Fibar Group Dimmer (20.1)","level":0},"permanently_hidden":true,"probeType":"dimmer","tags":[],"visibility":true,"updateTime":1458117650},{"creationTime":1456245361,"creatorId":1,"deviceType":"switchMultilevel","h":-844530992,"hasHistory":false,"id":"ZWayVDev_zway_20-2-38","location":4,"metrics":{"icon":"multilevel","title":"Fibar Group Dimmer (20.2)","level":99},"permanently_hidden":false,"probeType":"dimmer","tags":[],"visibility":true,"updateTime":1458117614},{"creationTime":1455645602,"creatorId":1,"deviceType":"sensorBinary","h":567851557,"hasHistory":false,"id":"ZWayVDev_zway_20-0-113-4-254-A","location":4,"metrics":{"icon":"alarm","level":"on","title":"Fibar Group Heat Alarm (20.0.113.4.254)"},"permanently_hidden":true,"probeType":"alarm_heat","tags":[],"visibility":true,"updateTime":1458122404},{"creationTime":1455645602,"creatorId":1,"deviceType":"sensorBinary","h":-177101015,"hasHistory":false,"id":"ZWayVDev_zway_20-0-113-8-254-A","location":4,"metrics":{"icon":"alarm","level":"on","title":"Fibar Group Power Management Alarm (20.0.113.8.254)"},"permanently_hidden":true,"probeType":"alarm_power","tags":[],"visibility":true,"updateTime":1458122404},{"creationTime":1455645602,"creatorId":1,"deviceType":"sensorBinary","h":710402666,"hasHistory":false,"id":"ZWayVDev_zway_20-0-113-9-254-A","location":4,"metrics":{"icon":"alarm","level":"on","title":"Fibar Group System Alarm (20.0.113.9.254)"},"permanently_hidden":true,"probeType":"alarm_system","tags":[],"visibility":true,"updateTime":1458122404},{"creationTime":1455905178,"creatorId":1,"deviceType":"sensorMultilevel","h":125938680,"hasHistory":false,"id":"ZWayVDev_zway_20-1-49-4","location":4,"metrics":{"probeTitle":"Power","scaleTitle":"W","level":0,"icon":"energy","title":"Fibar Group Power (20.1.49.4)"},"permanently_hidden":true,"probeType":"energy","tags":[],"visibility":true,"updateTime":1458121254}]},"code":200,"message":"200 OK","error":null}

I have 3 flood sensors (for now they only report temperature to my homekit app):
1. Bath Flood sensor
2. WC Flood Senor
3. Kitchen Flood Sensor

I appreciate your help and effort.

**Comment by zeair** [comment]
Hi. Any progess on this?

**Comment by SphtKr** [comment]
Hi @zeair , I'm back to working on this and just paired my Aeon Labs water sensor. Expect an update in about a week.

**Comment by SphtKr** [comment]
Added in 969d905, release 0.5.0-alpha4. Tested with Aeon Labs water sensor device. Please open a new issue if your water/leak detector device is not working!
