### ISSUE TITLE
Time-out on window covering

### ISSUE THREAD

**Issue by ibjr** [SphtKr/homebridge-zway#20]
Razberry/z-wave V2.2.1
Node V5.5.0
Homebridge 0.3.1
Homebridge-zway 0.5.0-alpha0
Device : Forest Motor Control Device (motorised window covers)
Eve - latest version on iOS 9.2.1

When I change (in Eve) the percentage ('Position') of the window covers from 100% to e.g. 80%, the covers start moving till approx 80%, that works fine. But on Eve a "moving circle" starts rotating (just in front of the 'down' and 'up' buttons); that lasts for 1 minute, and then the 'circle' stops rotating, and an error condition is reported (red triangle with explanation mark in it. Also, the percentage goes back to 100% until I "reload" the room in Eve (red triangle stays however).
During this one minute period, no other actions can be performed via Eve.
This happens always, for every change in percentage.

No error reports in homebridge or -z-way server.

**Comment by SphtKr** [comment]
Thanks for this report, I've seen this in the new WindowCovering support but wasn't sure if it was something in my environment--now I know it's not.

I've got a couple of additional features to add in the 0.5 before final release, I'll intend on resolving this bug before that release.

**Comment by SphtKr** [comment]
Fixed in c074aabaf4f50019d2545b6bad4eda82d846ddad.

**Comment by ibjr** [comment]
works fine now, great

Thanks,

Ino Rots


Op 29-5-2016 om 7:46 schreef SphtKr:
