### ISSUE TITLE
Z-way HTTPDevice

### ISSUE THREAD

**Issue by ohjay93** [SphtKr/homebridge-zway#24]
It would be fantastic if this plugin would also support HTTPDevices!
-I have built several ESP8266 temperature/humidity sensors that I access from Adafruit.io and expose to Z-way as HTTPDevices. Having these readings (and other DIY devices) showing up in Homekit would be awesome!

**Comment by SphtKr** [comment]
Hmm... I'm not sure what these devices look like in the API output. Can you provide me with your devices data from Z-Way? You'll need to login to the Z-Way standard UI--e.g. at http://your.pi.i.p:8083/, and then from that same browser window hit http://your.pi.i.p:8083/ZAutomation/api/v1/devices (replacing your.pi.i.p with your device's IP address of course), and attach or post the contents here.

**Comment by ohjay93** [comment]
Here is my readout. A good example is the last entry at the very bottom: "HTTP_Device_sensorMultilevel_24"
I've experimented with different tags, but so far I have only been able to make them show up in homekit as featureless devices, i.e without any readouts.

`{"data":{"structureChanged":true,"updateTime":1460145273,"devices":[{"creationTime":1459372722,"deviceType":"switchControl","h":1386268246,"hasHistory":false,"id":"ZWayVDev_zway_Remote_10-1-1-B","location":0,"metrics":{"icon":"","title":"Fibar Group (10.1.1) Button","level":"off","change":""},"permanently_hidden":true,"probeType":"","tags":[],"visibility":true,"updateTime":1459581429},{"creationTime":1459401499,"deviceType":"switchControl","h":-2022119851,"hasHistory":false,"id":"ZWayVDev_zway_Remote_11-0-0-B","location":0,"metrics":{"icon":"","title":"Fibar Group (11.0.0) Button","level":"on","change":""},"permanently_hidden":false,"probeType":"","tags":[],"visibility":true,"updateTime":1459581429},{"creationTime":1459372470,"creatorId":8,"deviceType":"battery","h":-592588977,"hasHistory":false,"id":"BatteryPolling_8","location":0,"metrics":{"probeTitle":"Battery","scaleTitle":"%","title":"Battery digest 8","level":100},"permanently_hidden":false,"probeType":"","tags":[],"visibility":true,"updateTime":1459634663},{"creationTime":1459372653,"creatorId":1,"deviceType":"sensorBinary","h":1904763028,"hasHistory":false,"id":"ZWayVDev_zway_10-0-48-1","location":0,"metrics":{"probeTitle":"General purpose","scaleTitle":"","icon":"motion","level":"off","title":"X_Motion Sensor"},"permanently_hidden":false,"probeType":"general_purpose","tags":[],"visibility":true,"updateTime":1460144601},{"creationTime":1459372654,"creatorId":1,"deviceType":"sensorMultilevel","h":1904763989,"hasHistory":false,"id":"ZWayVDev_zway_10-0-49-1","location":0,"metrics":{"probeTitle":"Temperature","scaleTitle":"°C","level":22.2,"icon":"temperature","title":"X_Temperature"},"permanently_hidden":false,"probeType":"temperature","tags":[],"visibility":true,"updateTime":1460145203},{"creationTime":1459372654,"creatorId":1,"deviceType":"sensorMultilevel","h":1904763991,"hasHistory":false,"id":"ZWayVDev_zway_10-0-49-3","location":0,"metrics":{"probeTitle":"Luminiscence","scaleTitle":"Lux","level":0,"icon":"luminosity","title":"LUX"},"permanently_hidden":false,"probeType":"luminosity","tags":[],"visibility":true,"updateTime":1460144601},{"creationTime":1459372653,"creatorId":1,"deviceType":"battery","h":2139650891,"hasHistory":false,"id":"ZWayVDev_zway_10-0-128","location":0,"metrics":{"probeTitle":"Battery","scaleTitle":"%","level":100,"icon":"battery","title":"Fibar Group (10.0) Battery"},"permanently_hidden":false,"probeType":"","tags":[],"visibility":true,"updateTime":1459634663},{"creationTime":1459372654,"creatorId":1,"deviceType":"sensorBinary","h":1242261309,"hasHistory":false,"id":"ZWayVDev_zway_10-0-156-0-A","location":0,"metrics":{"icon":"alarm","level":"off","title":"Fibar Group General Purpose alarm (10.0.156.0) Alarm"},"permanently_hidden":false,"probeType":"alarmSensor_general_purpose","tags":[],"visibility":true,"updateTime":1460145203},{"creationTime":1459372901,"creatorId":1,"deviceType":"switchBinary","h":-1703465105,"hasHistory":false,"id":"ZWayVDev_zway_11-0-37","location":2,"metrics":{"icon":"switch","title":"Office Switch","level":"off"},"permanently_hidden":false,"probeType":"","tags":[],"visibility":true,"updateTime":1460145264},{"creationTime":1459372901,"creatorId":1,"deviceType":"sensorMultilevel","h":-647392969,"hasHistory":false,"id":"ZWayVDev_zway_11-0-49-4","location":2,"metrics":{"probeTitle":"Power","scaleTitle":"W","level":0,"icon":"energy","title":"Office Drain"},"permanently_hidden":false,"probeType":"energy","tags":[],"visibility":true,"updateTime":1460145025},{"creationTime":1459372902,"creatorId":1,"deviceType":"sensorMultilevel","h":-647371831,"hasHistory":false,"id":"ZWayVDev_zway_11-0-50-0","location":2,"metrics":{"probeTitle":"Electric","scaleTitle":"kWh","level":1520.6099968,"icon":"meter","title":"Office Usage"},"permanently_hidden":false,"probeType":"meterElectric_kilowatt_per_hour","tags":["Homebridge.Include"],"visibility":true,"updateTime":1460145000},{"creationTime":1459372902,"creatorId":1,"deviceType":"sensorMultilevel","h":-647371829,"hasHistory":false,"id":"ZWayVDev_zway_11-0-50-2","location":2,"metrics":{"probeTitle":"Electric","scaleTitle":"W","level":0,"icon":"meter","title":"Office Usage?"},"permanently_hidden":false,"probeType":"meterElectric_watt","tags":[],"visibility":true,"updateTime":1460144401},{"creationTime":1459373294,"creatorId":1,"deviceType":"switchBinary","h":-1674835954,"hasHistory":false,"id":"ZWayVDev_zway_12-0-37","location":1,"metrics":{"icon":"switch","title":"Living Room Switch","level":"on"},"permanently_hidden":false,"probeType":"","tags":[],"visibility":true,"updateTime":1460145254},{"creationTime":1459373294,"creatorId":1,"deviceType":"sensorMultilevel","h":1095417366,"hasHistory":false,"id":"ZWayVDev_zway_12-0-49-4","location":1,"metrics":{"probeTitle":"Power","scaleTitle":"W","level":993.900032,"icon":"energy","title":"Living Room Drain"},"permanently_hidden":false,"probeType":"energy","tags":[],"visibility":true,"updateTime":1460145001},{"creationTime":1459373294,"creatorId":1,"deviceType":"sensorMultilevel","h":1095438504,"hasHistory":false,"id":"ZWayVDev_zway_12-0-50-0","location":1,"metrics":{"probeTitle":"Electric","scaleTitle":"kWh","level":1707.010048,"icon":"meter","title":"Living Room Usage"},"permanently_hidden":false,"probeType":"meterElectric_kilowatt_per_hour","tags":["Homebridge.Include"],"visibility":true,"updateTime":1460145129},{"creationTime":1459373294,"creatorId":1,"deviceType":"sensorMultilevel","h":1095438506,"hasHistory":false,"id":"ZWayVDev_zway_12-0-50-2","location":0,"metrics":{"probeTitle":"Electric","scaleTitle":"W","level":993.900032,"icon":"meter","title":"Fibar Group Electric (12.0.50.2) Meter"},"permanently_hidden":false,"probeType":"meterElectric_watt","tags":[],"visibility":true,"updateTime":1460145001},{"creationTime":1459374824,"creatorId":10,"deviceType":"sensorMultilevel","h":-342320601,"hasHistory":false,"id":"HTTP_Device_sensorMultilevel_10","location":3,"metrics":{"scaleTitle":"°c","icon":"sensor","title":"X_Bedroom Temperature","level":15},"permanently_hidden":false,"probeType":"","tags":[],"visibility":true,"updateTime":1460145273},{"creationTime":1459375158,"creatorId":11,"deviceType":"sensorMultilevel","h":-342320600,"hasHistory":false,"id":"HTTP_Device_sensorMultilevel_11","location":1,"metrics":{"scaleTitle":"°c","icon":"sensor","title":"Living Room Temperature","level":21.3},"permanently_hidden":false,"probeType":"","tags":["Homebridge.Include","Homebridge.IsPrimary"],"visibility":true,"updateTime":1460145253},
{"creationTime":1459375366,"creatorId":12,"deviceType":"sensorMultilevel","h":-342320599,"hasHistory":false,"id":"HTTP_Device_sensorMultilevel_12","location":2,"metrics":{"scaleTitle":"°c","icon":"sensor","title":"Office Temperature","level":22.3},"permanently_hidden":false,"probeType":"","tags":["Homebridge.IsPrimary"],"visibility":true,"updateTime":1460145264},{"creationTime":1459434144,"creatorId":24,"deviceType":"sensorMultilevel","h":-342320566,"hasHistory":false,"id":"HTTP_Device_sensorMultilevel_24","location":0,"metrics":{"scaleTitle":"°c","icon":"sensor","title":"Outdoor Temperature","level":5.5},"permanently_hidden":false,"probeType":"","tags":[],"visibility":true,"updateTime":1460145253}]},"code":200,"message":"200 OK","error":null}`

**Comment by SphtKr** [comment]
Ah. That's fairly easy... I've got to let you set `Homebridge.Service.Type:TemperatureSensor` on a `sensorMultilevel` that doesn't specify its `probeType`. It opens some potential problems, but if you're doing custom devices I can assume you know what you're doing and it's your responsibility to get it right.

I don't suppose it's possible to make your HTTP device output its `probeType` as `temperature`? That would make it "just work".

Any other sensor types you have in mind besides temperature?

**Comment by ohjay93** [comment]
Great news :-) And thank you for your great work and quick response! 
If I could specify the probeType through a Tag it would be hunky-dory!

I don't know of a way to specify probeType on the HTTPDevice itself, It might be possible by modifying the Z-Wave framework itself, but that again might make it unstable.

For other devices i also have a humidity sensor (DHT22) 

`{
			"creationTime": 1460204395,
			"creatorId": 25,
			"deviceType": "sensorMultilevel",
			"h": -342320565,
			"hasHistory": false,
			"id": "HTTP_Device_sensorMultilevel_25",
			"location": 0,
			"metrics": {
				"scaleTitle": "%",
				"icon": "sensor",
				"title": "Humidity Sensor",
				"level": 36
			},
			"permanently_hidden": false,
			"probeType": "",
			"tags": [],
			"visibility": true,
			"updateTime": 1460204722
		}`

-This is also missing any probeType.

**Comment by epideme** [comment]
Great enhancement idea this.
HTTPDevice is really useful but does not let you select probeType. I solved it with an ugly hack of the plugin but got tired of maintaining it and ignored it eventually. Looking forward to the enhancement. Thanks!

**Comment by epideme** [comment]
Slightly off topic but felt it could be useful info: Maros at Zway just gave me a nice workaround to set probeType through the JS api.
http://yourserver:8083/JS/Run/controller.devices.get("HTTP_Device_sensorMultilevel_25").set("probeType","temperature")
Unfortunately this does not seem to be persistent after restart.

**Comment by SphtKr** [comment]
Not off topic at all. Pity it doesn't persist. FWIW, I imagine it would be possible to do that same thing in JS code in a code device, which would run at startup when the code device started. (Not that I've actually written any code devices myself, I'm assuming it would work.)

**Comment by lademeister** [comment]
Have you found a way to run the code in a code device to set it once on startup?
Would love to see example code, as I am having the same issue :-)
