### ISSUE TITLE
Fibaro Roller Shutter 2 Support

### ISSUE THREAD

**Issue by duncan82** [SphtKr/homebridge-zway#28]
Hi,

I recently set up my initial Razberry Pi and I am trying to get my Fibaro Roller Shutter 2 working in HomeKit with support of open/close/partially open messages.

The hardware I am using is:
 - Raspberry Pi 3
 - Z.Wave Me Z-Wave Plus Module (ZMEERAZ)
 - Fibaro Roller Shutter 2 (FGRM-222)

Software currently running is:
 - Z-Way Server v2.2.2
 - Homebridge 
 - homebridge-zway 0.5.0alpha2
 - Elgato Eve App 1.5 on iPad 4

I am trying to get the roller shutter to work with homebridge-zway. Using the switchBinary (device ZWayVDev_zway_2-0-37) is not a problem. However, it get's always displayed as "power".

However, I would love to use the switchMultilevel (device ZWayVDev_zway_2-0-38) as WindowCovering to be able to tell Siri to shut or open it. Whatever I have tried, the Eve app is not display the device when adding Homebridge. See screenshot attached.

I have tried out various configurations, but nothing led to the expected behavior.

Is there something I am missing out or is this currently not yet fully implemented? Or do I need to use a specific configuration to get the device working as expected?

The following commands have been tested and they work fine:
Completely opening the window blind:
http://raspberrypi:8083/ZAutomation/api/v1/devices/ZWayVDev_zway_2-0-38/command/on
Completely closing the window blind:
http://raspberrypi:8083/ZAutomation/api/v1/devices/ZWayVDev_zway_2-0-38/command/off
Setting to 75% open:
http://raspberrypi:8083/ZWaveAPI/Run/devices[2].instances[0].commandClasses[38].Set(75)

Any type of support is highly appreciated!

Thanks and best regards,
Lars

Attachments:
Devices from Z-Way
[devices.txt](https://github.com/SphtKr/homebridge-zway/files/222646/devices.txt)

Homebridge Start Up Log
[Homebridge_Start_Up_Log.txt](https://github.com/SphtKr/homebridge-zway/files/222648/Homebridge_Start_Up_Log.txt)

Homebridge Configuration
[homebridge_config.txt](https://github.com/SphtKr/homebridge-zway/files/222647/homebridge_config.txt)

**Comment by SphtKr** [comment]
Hello,

Two things going on here:

One is that Z-Way changed the way a BUNCH of devices are reported in their API in 2.2.2 :angry:. Now your device has a `probeType` of `motor`, which it wouldn't have had before 2.2.2, I'm pretty sure. So, I'll have to update for that.

Two, be advised that roller shutter support is a little buggy at the moment...they seem to time out after locking up after a minute (on the HomeKit side), and HomeKit always reports that they failed. So, once I get the above fixed, be aware that it may be a little annoying 😄 .

**Comment by duncan82** [comment]
Hi SphtKr,

thans for the quick feedback! I downgraded to 2.2.1 and it works as now I can use the percentages within Siri automation!

However, I do see what you mean with the unstable support of roller shutter. But I was prepared, so I can live with it for now! Thanks a lot!

I will regularly check back here for sure. :)

Best,
Lars

**Comment by SphtKr** [comment]
Fixed in c074aabaf4f50019d2545b6bad4eda82d846ddad.
