### ISSUE TITLE
Doesn't seem to work properly with Z-Way v2.2.2

### ISSUE THREAD

**Issue by leonmf** [SphtKr/homebridge-zway#29]
I would have attached the accessories folder but it was empty.

I wound up reverting to v2.2.1 and things are working again.

**Comment by SphtKr** [comment]
Yes, this is a known issue. There are some fixes already in [this branch](https://github.com/SphtKr/homebridge-zway/tree/z-way-2-2-2-fixes), but to really fix it I need to upgrade my own system...which will break everything in my house. Gotta do it soon though.

**Comment by leonmf** [comment]
Ok, no worries then. I'm happy sticking with 2.2.1 until it's fixed. I just wanted to make sure it wasn't an unknown issue. 

PS: this works pretty awesomely overall. You have my eternal gratitude.
