### ISSUE TITLE
Qubino flush shutter DC in Homebridge

### ISSUE THREAD

**Issue by jsve** [SphtKr/homebridge-zway#30]
This might be related to bug #28.

I have a "Qubino flush shutter DC" (http://qubino.com/products/flush-shutter-dc/) that doesn't get recognised in homekit apps. It works fine in the zway web interface and app.

The hardware I am using is:
- Raspberry Pi 3
- Raspberry PI GPIO module (based on ZM5202)
- Qubino flush shutter DC

Software currently running is:
- Z-Way Server v2.2.2
- Homebridge
- homebridge-zway 0.5.0-alpha2

I get the warning that there is only a "informationservice" registered and no devices. See the log below.

What i did try was to try to separate the different controllers in the Z-Way server. The Qubino has 4 "devices" registered there: two power-measurers, one continuous controller and one switch. When i separate the switch with "Homebridge.Accessory.Id:value" I can control simple up and down, however it registers as always on (fully up).

I will try downgrading the server as suggested in #28.

The log:
[5/4/2016, 5:25:55 AM] Initializing ZWayServer platform...
  ZWayServer Fetching Z-Way devices... +0ms
[5/4/2016, 5:25:55 AM] Loading 0 accessories...
  ZWayServer Authenticating... +162ms
  ZWayServer Authenticated. Resubmitting original request... +79ms
  ZWayServer Got typeKey text for vdev InfoWidget_5_Int +43ms
  ZWayServer { deviceType: 'text', probeTitle: undefined, probeType: '' } +1ms
  ZWayServer Got typeKey battery.Battery for vdev BatteryPolling_7 +80ms
  ZWayServer { deviceType: 'battery', probeTitle: 'Battery', probeType: '' } +0ms
  ZWayServer Got typeKey switchBinary for vdev ZWayVDev_zway_2-0-37 +3ms
  ZWayServer { deviceType: 'switchBinary', probeTitle: undefined, probeType: '' } +1ms
  ZWayServer Got typeKey sensorMultilevel.meterElectric_kilowatt_per_hour for vdev ZWayVDev_zway_2-0-50-0 +2ms
  ZWayServer { deviceType: 'sensorMultilevel', probeTitle: 'Electric', probeType: 'meterElectric_kilowatt_per_hour' } +0ms
  ZWayServer Got typeKey sensorMultilevel.meterElectric_watt for vdev ZWayVDev_zway_2-0-50-2 +2ms
  ZWayServer { deviceType: 'sensorMultilevel', probeTitle: 'Electric', probeType: 'meterElectric_watt' } +0ms
  ZWayServer Got typeKey switchBinary for vdev ZWayVDev_zway_3-0-37 +1ms
  ZWayServer { deviceType: 'switchBinary', probeTitle: undefined, probeType: '' } +0ms
  ZWayServer Got typeKey switchMultilevel.motor for vdev ZWayVDev_zway_3-0-38 +1ms
  ZWayServer { deviceType: 'switchMultilevel', probeTitle: undefined, probeType: 'motor' } +0ms
  ZWayServer Got typeKey sensorMultilevel.meterElectric_kilowatt_per_hour for vdev ZWayVDev_zway_3-0-50-0 +3ms
  ZWayServer { deviceType: 'sensorMultilevel', probeTitle: 'Electric', probeType: 'meterElectric_kilowatt_per_hour' } +0ms
  ZWayServer Got typeKey sensorMultilevel.meterElectric_watt for vdev ZWayVDev_zway_3-0-50-2 +1ms
  ZWayServer { deviceType: 'sensorMultilevel', probeTitle: 'Electric', probeType: 'meterElectric_watt' } +0ms
  ZWayServer Got grouped device InfoWidget_5_Int consisting of devices: +1ms
  ZWayServer InfoWidget_5_Int - text +0ms
  ZWayServer WARN: Didn't find suitable device class! +1ms
  ZWayServer Got grouped device BatteryPolling_7 consisting of devices: +0ms
  ZWayServer BatteryPolling_7 - battery.Battery +0ms
  ZWayServer WARN: Didn't find suitable device class! +0ms
  ZWayServer Got grouped device ZWayVDev_2-0 consisting of devices: +0ms
  ZWayServer ZWayVDev_zway_2-0-37 - switchBinary +0ms
  ZWayServer ZWayVDev_zway_2-0-50-0 - sensorMultilevel.Electric +0ms
  ZWayServer ZWayVDev_zway_2-0-50-2 - sensorMultilevel.Electric +0ms
  ZWayServer Got grouped device ZWayVDev_3-0 consisting of devices: +1ms
  ZWayServer ZWayVDev_zway_3-0-37 - switchBinary +0ms
  ZWayServer ZWayVDev_zway_3-0-38 - switchMultilevel +0ms
  ZWayServer ZWayVDev_zway_3-0-50-0 - sensorMultilevel.Electric +1ms
  ZWayServer ZWayVDev_zway_3-0-50-2 - sensorMultilevel.Electric +0ms
[5/4/2016, 5:25:55 AM] Initializing platform accessory 'L��slampa sovrum'...
  ZWayServer Got typeKey switchBinary for vdev ZWayVDev_zway_2-0-37 +17ms
  ZWayServer { deviceType: 'switchBinary', probeTitle: undefined, probeType: '' } +0ms
  ZWayServer Got typeKey switchBinary for vdev ZWayVDev_zway_2-0-37 +40ms
  ZWayServer { deviceType: 'switchBinary', probeTitle: undefined, probeType: '' } +1ms
  ZWayServer Got typeKey sensorMultilevel.meterElectric_watt for vdev ZWayVDev_zway_2-0-50-2 +3ms
  ZWayServer { deviceType: 'sensorMultilevel', probeTitle: 'Electric', probeType: 'meterElectric_watt' } +0ms
  ZWayServer Got typeKey sensorMultilevel.meterElectric_watt for vdev ZWayVDev_zway_2-0-50-2 +4ms
  ZWayServer { deviceType: 'sensorMultilevel', probeTitle: 'Electric', probeType: 'meterElectric_watt' } +0ms
  ZWayServer Got typeKey switchBinary for vdev ZWayVDev_zway_2-0-37 +2ms
  ZWayServer { deviceType: 'switchBinary', probeTitle: undefined, probeType: '' } +1ms
  ZWayServer Got typeKey switchBinary for vdev ZWayVDev_zway_2-0-37 +1ms
  ZWayServer { deviceType: 'switchBinary', probeTitle: undefined, probeType: '' } +1ms
  ZWayServer Got typeKey sensorMultilevel.meterElectric_kilowatt_per_hour for vdev ZWayVDev_zway_2-0-50-0 +0ms
  ZWayServer { deviceType: 'sensorMultilevel', probeTitle: 'Electric', probeType: 'meterElectric_kilowatt_per_hour' } +1ms
  ZWayServer Got typeKey sensorMultilevel.meterElectric_watt for vdev ZWayVDev_zway_2-0-50-2 +0ms
  ZWayServer { deviceType: 'sensorMultilevel', probeTitle: 'Electric', probeType: 'meterElectric_watt' } +0ms
  ZWayServer Got typeKey sensorMultilevel.meterElectric_watt for vdev ZWayVDev_zway_2-0-50-2 +7ms
  ZWayServer { deviceType: 'sensorMultilevel', probeTitle: 'Electric', probeType: 'meterElectric_watt' } +0ms
  ZWayServer Got typeKey sensorMultilevel.meterElectric_watt for vdev ZWayVDev_zway_2-0-50-2 +5ms
  ZWayServer { deviceType: 'sensorMultilevel', probeTitle: 'Electric', probeType: 'meterElectric_watt' } +1ms
  ZWayServer Got typeKey switchBinary for vdev ZWayVDev_zway_2-0-37 +0ms
  ZWayServer { deviceType: 'switchBinary', probeTitle: undefined, probeType: '' } +1ms
  ZWayServer Got typeKey sensorMultilevel.meterElectric_kilowatt_per_hour for vdev ZWayVDev_zway_2-0-50-0 +0ms
  ZWayServer { deviceType: 'sensorMultilevel', probeTitle: 'Electric', probeType: 'meterElectric_kilowatt_per_hour' } +0ms
  ZWayServer Loaded services for L��slampa sovrum +5ms
[5/4/2016, 5:25:55 AM] Initializing platform accessory 'Rullgardiner sovrum'...
  ZWayServer Got typeKey switchMultilevel.motor for vdev ZWayVDev_zway_3-0-38 +16ms
  ZWayServer { deviceType: 'switchMultilevel', probeTitle: undefined, probeType: 'motor' } +1ms
  ZWayServer WARN: Only the InformationService was successfully configured for ZWayVDev_zway_3-0-38! No device services available! +1ms

**Comment by emilp333** [comment]
It is related to issue #15.

**Comment by SphtKr** [comment]
And likely #27 , since you're running Z-Way 2.2.2 . They changed all the `probeType` values in the API, it seems. 😠

**Comment by SphtKr** [comment]
Fixed in c074aabaf4f50019d2545b6bad4eda82d846ddad.
