### ISSUE TITLE
Z-Way with new webserver 

### ISSUE THREAD

**Issue by aivs** [SphtKr/homebridge-zway#36]
Hi SphtKr, are you tested homebridge-zway with the latest z-way with new webserver ?
http://razberry.z-wave.me/z-way-server/z-way-server-RaspberryPiXTools-v2.2.2-test-new-webserver-5-gba57763.tgz

I tried on raspberry b+ with nodejs v4.4.5. The problem with security exists:
```
pi@raspberrypi /usr/local/lib/node_modules/homebridge $ sudo DEBUG=* homebridge -U ./
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[6/1/2016, 5:05:03 PM] Loaded plugin: homebridge-zway
[6/1/2016, 5:05:03 PM] Registering accessory 'homebridge-zway.ZWayServer'
[6/1/2016, 5:05:03 PM] Registering platform 'homebridge-zway.ZWayServer'
[6/1/2016, 5:05:03 PM] ---
[6/1/2016, 5:05:03 PM] Loaded config.json with 0 accessories and 1 platforms.
[6/1/2016, 5:05:03 PM] ---
[6/1/2016, 5:05:03 PM] Loading 1 platforms...
[6/1/2016, 5:05:03 PM] Initializing ZWayServer platform...
  ZWayServer Fetching Z-Way devices... +0ms
  ZWayServer ERROR: Request failed! +670ms
  ZWayServer Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14) +21ms
```

Will decide

**Comment by aivs** [comment]
With right config.json all work fine:
` {
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "Z-Wave controller",
    "platforms": [
    {
            "platform": "ZWayServer",
            "url": "http://localhost:8083/",
            "login": "admin",
            "password": "admin"
    }    
    ]
}`

In url last symbol "/" very important!!!!

**Comment by SphtKr** [comment]
Hmm! When I updated to 2.2.2 I noticed that "test-new-webserver" bit, and I wondered if that fixed the node client issue. I haven't switched back to the latest node yet to test (using 4.2.0 as a workaround), but I will soon to check it out!

**Comment by SphtKr** [comment]
Indeed, it looks like 2.2.2-test-new-webserver has resolved the Node vs. Z-Way compatibility issue! Closing this and #14.
