### ISSUE TITLE
Update to latest alpha?

### ISSUE THREAD

**Issue by DJay1** [SphtKr/homebridge-zway#37]
I'm sure I'm doing something wrong.
How can I update to the latest alpha?
sudo npm install --unsafe-perm -g homebridge-zway
This brings always 0.4.0
Sorry to bother and thx in advance for the help.

pi@raspberrypi / $ npm list homebridge-zway -g
/usr/local/lib
└── homebridge-zway@0.4.0 

pi@raspberrypi / $ npm info homebridge-zway version
0.5.0-alpha3

**Comment by SphtKr** [comment]
This should do it:

    npm install -g homebridge-zway@0.5.0-alpha3

(Though I guess you also need `--unsafe-perm` for your installation...I won't put it in the snippet above in case someone else comes along and just copy-pastes it in)

**Comment by DJay1** [comment]
That's it. Great. Thanks a lot.
