### ISSUE TITLE
Homebridge doesn't launch when Z-Way added to platforms

### ISSUE THREAD

**Issue by jsg4** [SphtKr/homebridge-zway#38]
Weird thing I am seeing, whenever I try and launch Homebridge with z-way in the config file, homebridge does not launch. If I take it out, everything is great. I have tried uninstalling, installing again, installing latest alpha release, still doesn't matter. I am using the IP address with port, my username and password.

If I use the HomeKit app on the Razpberry, I can add that to HomeKit.

**Comment by SphtKr** [comment]
Hi @jsg4 , can you start homebridge with the command `DEBUG=* homebridge` and attach the output here?

**Comment by jsg4** [comment]
ZWayServer ERROR: Request failed! +124ms
  ZWayServer Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:320:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20) +1ms

Thanks!

**Comment by jsg4** [comment]
Also I am running version 2.2.2 in case that matters.

**Comment by SphtKr** [comment]
Okay. First, if you're on 2.2.2 you'll need the latest v0.5.0-alpha. See #37 if you need the command to make sure you get it, you may be on 0.4.x at the moment.

Second, honestly that looks like you've got the wrong URL or port for Z-Way in your `config.json`. Or something else is preventing homebridge from accessing it via http. Make sure of a few things:

```
"platforms": [
    {
        "platform": "ZWayServer",
        "url": "http://your.ip.goes.here:8083/",
        "login": "[admin]",
        "password": "[password]"
    }
]
```

The `/` at the end of the `url` parameter is important, if it's not there. Make sure you haven't changed the port or something (8083 is the default), or if you're running it via an SSL proxy then make `http` into `https`, that sort of thing.

If the URL looks all correct, then make sure you can actually hit that URL from the system where Homebridge is running (e.g. if you're running Homebridge on a Mac and Z-Way on an RPi, make sure you can reach Z-Way from the Mac's browser.

**Comment by jsg4** [comment]
Thanks! I am running the 0.5 alpha, I can access the Razberry page through my browser on the Mac I am running homebridge on, can't think of anything else. I even made a new user and tried with that too. Here is the log from just now, same thing.

  ZWayServer ERROR: Request failed! +182ms
  ZWayServer Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:320:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20) +0ms

**Comment by jsg4** [comment]
Here's what is in config file.

		"platform": "ZWayServer",
    "url": "http://192.168.1.242:8083/",
    "login": "homebridge",
    "password": "password"

**Comment by SphtKr** [comment]
Ugh. Okay, from your Mac, in terminal, can you run the following command:

    curl http://192.168.1.242:8083/ZAutomation/api/v1/devices

FWIW, I'd expect something like this:

    {"data":null,"code":401,"message":"401 Unauthorized","error":"Not logged in"}

**Comment by jsg4** [comment]
Yes.

Jonathans-Mac-mini:~ jonathan$ curl http://192.168.1.242:8083/ZAutomation/api/v1/devices
{"data":null,"code":401,"message":"401 Unauthorized","error":"Not logged in"}

**Comment by Zyg0te** [comment]
For what it's worth, I am also having an issue with this plugin. The Homebridge server starts but it just hangs at `Initializing platform accessory`. If I remove the ZWayServer platform, Homebridge runs just fine.

Any ideas?

**Comment by Zyg0te** [comment]
Here's the debug output.

```
ZWayServer ERROR: Request failed! +539ms
  ZWayServer Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20) +4ms
```

**Comment by Zyg0te** [comment]
@jsg4 Did you mange to resolve this issue?

**Comment by 100hz** [comment]
@jsg4 #14 may depend on your node version

**Comment by jsg4** [comment]
I'm on 4.0.0

**Comment by Zyg0te** [comment]
I'm on 6.2.2 so that might be the issue. It's a bit of a pain to downgrade though. I reckon I would have to re-install homebridge as well?

**Comment by Zyg0te** [comment]
with v2.2.2-test-new-webserver-8-ga9cd319 everything works fine here. Awesome stuff!

**Comment by jsg4** [comment]
Where did you see that? And do I update to that? Thanks!

**Comment by Zyg0te** [comment]
@jsg4 Just go to the Z-wave firmware update control and specify the firmware version to install manually: `v2.2.2-test-new-webserver-8-ga9cd319` Then click update.

**Comment by moosebert** [comment]
I think I might be having the same issue, or at least one very similar.  Running Z-Way server 2.2.3, latest homebridge-zway alpha (5).  

Homebridge fires up just fine sans the zway platform, but with zway platform included in the config.json other platforms (Nest, as an example) load fine but homebridge never shows the "scan this code" bit, mDNS seems DOA.  Everything looks like it loads just fine, same normal output.

With debug on (via enabling DEBUG in systemd config) I only see the following additional output:

Thu, 28 Jul 2016 21:55:20 GMT ZWayServer Fetching Z-Way devices...
Thu, 28 Jul 2016 21:55:20 GMT ZWayServer Authenticating...

I can curl to the "http://localhost:8083/" URL in config.json, using the same credentials, but looking at a network trace on loopback when homebridge fires up I'm seeing 401s, namely unauthorized access returns.

**Comment by pps83** [comment]
I have the same error:
```

Error: Parse Error
    at Error (native)
    at Socket.socketOnData (_http_client.js:361:20)
    at readableAddChunk (_stream_readable.js:177:18)
```

However, I'm simply writing basic node code that has nothing to do with homebridge-zway

**Comment by SphtKr** [comment]
Hey folks, just now getting back to some of these, sorry. Looks like the original issue was related to #14. Closing this one, @pps83 if you're still having trouble please open a new issue, as it looks like a separate problem.
