### ISSUE TITLE
Bosch Home Connect 

### ISSUE THREAD

**Issue by DJay1** [SphtKr/homebridge-zway#39]
Guys I hope I'm on the right place here. Otherwise sorry. I bought a Bosch coffee maker CTL636ES6 with Home Connect feature. Works great with the App on iOS. But of course I'm curious if someone is getting this to work with Homebridge as a plug in or zway. https://developer.home-connect.com
If there is something I can help as a user of course please let me know. 
Thx, DJay

**Comment by SphtKr** [comment]
Hi DJay1, probably the best place to ask this is the slack instance for Homebridge on https://homebridgeteam.slack.com/ .
