### ISSUE TITLE
Lock states always "unlocking"/"unsecured"

### ISSUE THREAD

**Issue by moosebert** [SphtKr/homebridge-zway#44]
Have a couple Kiwkset locks successfully linked-up with Z-Way, but when presented to Homebridge as accessories they’re constantly showing “unlocking” (in iOS 10’s new Home app), and in a “Lock Mechanism Target State” of “Unsecured” constantly (despite being locked).

I’m able to lock/unlock them (with a valid state update) via Z-Way without issue.  It’s only via Homebridge that this funky “always unlocking” state appears.

**Comment by Zyg0te** [comment]
Same issue here with the Danalock. I can lock/unlock it with Siri just
fine, but using a HomeKit app I have to toggle the target state a few times
before it actually does anything.

Edvard;

**Comment by moosebert** [comment]
Found something interesting when digging through logs:
```ZWayServer Getting value for Entryway door deadbolt, characteristic "Lock Target State".```

This suggests to me that the "Lock Target State" attribute is something Z-Way is reading from the Lock, or manages itself.  How close am I there?

Or is homebridge-zway plugin simply trying to assign a value to the state, e.g. fill in a blank for what's described in https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/HomeKitDeveloperGuide/AccessingServicesandTheirCharacteristics/AccessingServicesandTheirCharacteristics.html ?

**Comment by moosebert** [comment]
Think I'm onto something here.  

So on line 1140 of index.js val is declared with a default value of "0".  If vdev.metrics.level returns "open", it should be set to "0" and conversely if "closed" is returned set to "1".  Did a little debugging, and at least with Z-Way 2.2.3 (only version I've ever used) if a lock is secured (e.g. "closed") vdev.metrics.level actually returns "close", ergo no match so val is never changed from "0".

Changed the code around simply like this and things are working as expected now:

`        if(cx instanceof Characteristic.LockTargetState){
            cx.zway_getValueFromVDev = function(vdev){
                var val = Characteristic.LockTargetState.UNSECURED;
                if(vdev.metrics.level === "open"){
                    val = Characteristic.LockTargetState.UNSECURED;
                } else if(vdev.metrics.level === "closed") {
                    val = Characteristic.LockTargetState.SECURED;
                } else if(vdev.metrics.level === "close") {
                    val = Characteristic.LockTargetState.SECURED;
                }
                debug("Returning LockTargetState of \"" + val + "\" because vdev.metrics.level returned \"" + vdev.metrics.level + "\"");
                return val;
            };`

Will submit a commit eventually on the above once I've researched more and validated it's the right approach.

Last issue is the status never changes within homekit after a successful lock/unlock.  Not sure if Z-Way server isn't triggering a device status update, or if homebridge-zway should be, but either way we never get a status change unless I go into the Z-Way server and manually ask for a status update.

**Comment by moosebert** [comment]
Resolved the "last issue" which has nothing to do with homebridge-zway.  Details at https://forum.z-wave.me/viewtopic.php?f=3419&t=23601 (use https://github.com/jensmoes/Niffler app).

With submitted commit this should be resolved.

@Zyg0te take a look at the aforementioned commit, and app.  Combo of these should solve your issues too I hope!

**Comment by Zyg0te** [comment]
@moosebert Thanks for looking into this. I have no experience with npm packages. How can I try out your commit exactly?

**Comment by moosebert** [comment]
@archpoint you can simply alter `/usr/lib/node_modules/homebridge-zway/index.js` on your box as described in this thread.

**Comment by archpoint** [comment]
@moosebert Gave it a go now. Works perfectly. Thank you.

**Comment by SphtKr** [comment]
@moosebert , Great! Thanks... I got my DanaLock but haven't installed it yet so couldn't test (finally ordered the right cylinder so it's on its way now). Can you submit this as a pull request?

**Comment by moosebert** [comment]
@SphtKr my pleasure dude, thanks for all the hard work.  Aforementioned "fix" can be found in pull req. #45

**Comment by Fingerz** [comment]
Have these changes been rolled into the latest v0.5 alpha (3)? From a cursory glance it seems to be but the code is not exactly the same as what's described above. I've also setup Niffler in my ZWay server but I'm not sure it's updating status correctly for my Danalock v2 BTZE. Home app on my iPhone always shows "Unlocking..." except for a few seconds after I try to lock the door, then it switches back. How can I verify that the ZWay + Niffler combination is working before I start debugging homebridge-zway?

**Comment by gijoecool** [comment]
No, these changes were added after 0.5.0-alpha3. Try updating to the latest (0.5.0-alpha4).

**Comment by Fingerz** [comment]
That did the trick (upgrading to 0.5.0-alpha4)! The status of my Danalock is now correctly updated in HomeKit.
