### ISSUE TITLE
Code devices binary switch as window blinds 

### ISSUE THREAD

**Issue by lademeister** [SphtKr/homebridge-zway#46]
I am using 2.2.2 new-webserver and homebridge-zway.
I am able to control zway code devices (binary switch) as light bulbs so Siri switches 433mhz devices as well as zwave devices as light bulbs.
But I also have a window blind that is only a 433mhz switch, but I want it to be recognized as window blind - without percentage because it only has open or closed state (on/off state of the switch).
Is there any way to do this?

I appreciate your work so much, I am in love with what's already possible :-)

**Comment by SphtKr** [comment]
Related to #24, will probably fix both together.

**Comment by SphtKr** [comment]
Oh...also related to #43, since it's a binary window covering control.

**Comment by SphtKr** [comment]
Believed resolved in 969d905, release 0.5.0-alpha4. Use the new tag `Homebridge.Override.probeType`, see README.md. Reopen if still not working!
