### ISSUE TITLE
Request: setup instructions

### ISSUE THREAD

**Issue by m0rph13** [SphtKr/homebridge-zway#5]
Please provide some setup instructions
1. sudo npm install -g homebridge
2. sudo npm install -g homebridge-zway
3. edit .homebridge/json.config and add the mentioned platform configuration as a node under platforms

**Comment by SphtKr** [comment]
Good idea, thanks... does that look good or should I add more?

**Comment by m0rph13** [comment]
Yeah, something like that, and some note that this is in fact a plugin for homebridge :)
Thank you for an awesome project btw!

**Comment by m0rph13** [comment]
yeah, sweet, thanks!

**Comment by SphtKr** [comment]
Closed in #3
