### ISSUE TITLE
Home App does gets no response from devices at start

### ISSUE THREAD

**Issue by peshay** [SphtKr/homebridge-zway#51]
Since I added a 6th devices which is maybe a bit out of range I have a problem with my Home App.
Everytime I open the iOS Home app, it shows me that every devices gives no response. Then I tap all the devices to get them answered and it works again, except two devices which stay as No Response. In Z-Way Server I can control the two devices normally. 
Following devices say no response in the Home App: 
"Heizung Kinderzimmer" and "Heizung Schlafzimmer"

[devices.json.txt](https://github.com/SphtKr/homebridge-zway/files/505031/devices.json.txt)
[accessories.txt](https://github.com/SphtKr/homebridge-zway/files/505032/accessories.txt)

**Comment by SphtKr** [comment]
I have about 40 devices, and I don't have his exact same problem at least...you should be fine. :-)

Can you tell me what version of Homebridge you're running? I haven't tested under 0.4.x yet, and that could be a factor.

**Comment by peshay** [comment]
I have 0.3.4

**Comment by SphtKr** [comment]
Okay, that's what I'm running, so good...are you running this on the RPi? What model? And what version of Nodejs?

**Comment by peshay** [comment]
Model 2 with Raspbian 8 , 2.14.7

**Comment by peshay** [comment]
To explain the behavior a bit better:
I open the Home App, on the first Screen of favorites, all devices are red, saying no response. I get them activated by tapping or if I go to a room, all devices in that room are then active at the main screen as well. Rooms I did not opened show their devices in the main screen still with no response.
I also connected my AppleTV to Homekit.

**Comment by SphtKr** [comment]
Great, that's helpful. It occurred to me after I bragged about running 40 devices that I'm running this on a Mac mini and I haven't yet tried that many on a Pi. But, I would expect that your Pi2 should be able to handle at least what you've got. 

Another question, sorry, do you have any other modules loaded in Homebridge? Or only the ZWay platform? What I am wondering is if accessories from other plugins do the same thing, it might be Homebridge or something else in your system. If other plugins work as expected, then it's definitely something in the ZWay module. If you don't have any other plugins installed, could you find another one to test and see if it behaves as expected? Like the command line plugin or something?

**Comment by peshay** [comment]
Okay you're right. Same problem with homebridge-cmd. Automatic refresh on main screen fails on all devices, no matter how many are in my favorites, even if it's just a single device.
