### ISSUE TITLE
Fibaro Window Sensor Support

### ISSUE THREAD

**Issue by peshay** [SphtKr/homebridge-zway#53]
I have a Fibaro Window Sensor, but whatever tags I use, it's shown as not supported in Homekit.  
[accessories-2.txt](https://github.com/SphtKr/homebridge-zway/files/518980/accessories-2.txt)
[devices.json.txt](https://github.com/SphtKr/homebridge-zway/files/518981/devices.json.txt)

**Comment by SphtKr** [comment]
I think I see the problem--your sensor is reporting as `general_purpose`, and that type is not in the list to be able to be changed to a door, window or contact sensor. I'll have to add that to the list.

**Comment by klaasjoerg** [comment]
While fumbling around in on behalf of the other issue #56, was just also quick n dirty playing around to somehow get also my fibaro door sensor running (somehow). It works now, but it's of course completely unofficial and without warranty ;-) 
In case you wanna try it, attached is my index.js I modified accordingly.
[index_js.txt](https://github.com/SphtKr/homebridge-zway/files/532055/index_js.txt)
