### ISSUE TITLE
Homebridge quits as soon as fibaro motion sensor is being activated

### ISSUE THREAD

**Issue by klaasjoerg** [SphtKr/homebridge-zway#55]
As started/ended in discusson of ticket #21 here a new branch of the same effect:

As soon as I add/activate the fibaro motion sensor , homebridge doesn't start up anymore. (see latest comments thread in #21) .
Activating the fibaros Temperature or tamper alarm device doesnt create any problems. This issue happened suddenly as everything used to work fine before. So not really knowing what's the root change caused this.

Attached is my zwave.me - devices.json file:
[devices_json.txt](https://github.com/SphtKr/homebridge-zway/files/531063/devices_json.txt)

Thanks for helping.

This is one of the two devices causing my problem: 
4    Garagenauge                4.55.00 Fibar Group     Motion Sensor (Multi-Sensor)    2.7     Routing Binary Sensor

**Comment by klaasjoerg** [comment]
Btw: Where can I see what firmware-version is currently running on the fibaro motion sensor?

**Comment by klaasjoerg** [comment]
I clicked on Interview results and then an "version", an got the following results below. If I read it read correctly there is firmware 2.7 running on both devices...

_/: None (24.09.2016)
    supported: true (24.09.2016)
    version: 2 (24.09.2016)
    security: false (24.09.2016)
    interviewDone: true (24.09.2016)
    interviewCounter: 9 (24.09.2016)
    ZWLib: 3 (24.09.2016)
    ZWProtocolMajor: 3 (24.09.2016)
    ZWProtocolMinor: 67 (24.09.2016)
    SDK: 4.55.00 (24.09.2016)
    applicationMajor: 2 (24.09.2016)
    applicationMinor: 7 (24.09.2016)
    hardwareVersion: 1 (24.09.2016)
    firmwareCount: 1 (24.09.2016)
    firmware1: None (24.09.2016)
        major: 2 (24.09.2016)
        minor: 7 (24.09.2016)_

and for the other motion sensor I got:

_/: None (04.10.2016)
    supported: true (04.10.2016)
    version: 2 (04.10.2016)
    security: false (04.10.2016)
    interviewDone: true (04.10.2016)
    interviewCounter: 9 (04.10.2016)
    ZWLib: 3 (04.10.2016)
    ZWProtocolMajor: 3 (04.10.2016)
    ZWProtocolMinor: 67 (04.10.2016)
    SDK: 4.55.00 (04.10.2016)
    applicationMajor: 2 (04.10.2016)
    applicationMinor: 7 (04.10.2016)
    hardwareVersion: 1 (04.10.2016)
    firmwareCount: 1 (04.10.2016)
    firmware1: None (04.10.2016)
        major: 2 (04.10.2016)
        minor: 7 (04.10.2016)_

**Comment by klaasjoerg** [comment]
Was dealing with some further tuning and updating zway automator and smarthome-UI. However, at the end I re-activaed all devices/instances again and simply tried to restart homebridge and it didn't quit anymore. I have really no idea what changed/caused all this. 
Maybe my manual dev/stage updates of zway-server made a difference? Don't know.... But works again.

**Comment by SphtKr** [comment]
Can you add the following two tags to the "Garagenauge" device in Z-Way and see if it works:

`Homebridge.Service.Type:MotionSensor`
`Homebridge.Characteristic.Type:MotionDetected`

? I think I may see what's going on here. But that might work around the problem for you in the meantime and I'd be curious to know if it does.

**Comment by SphtKr** [comment]
Oops, had this tab open and just saw your last comment. That's puzzling, but there are a number of explanations. I'll continue looking at this, let me know if it acts up again.

**Comment by klaasjoerg** [comment]
Sure. But since then, it's working fine. No further problems.  (but as mentioned I also made a little change as mentioned in #53 )

**Comment by SphtKr** [comment]
@klaasjoerg , could you try out the code in pull request #62? I think it will solve your issues and at least be no worse than your edited version.

**Comment by SphtKr** [comment]
Believed fixed in 9d163e6, reopen or create a new issue if not fixed.
