### ISSUE TITLE
Honor "Homebridge.Skip" tag for sub-devices in grouped device list

### ISSUE THREAD

**Issue by johannrichard** [SphtKr/homebridge-zway#6]
I have an Aeon Labs Mini Double Switch that presents itself as a list of grouped devices with a "common" switch (3-0-37) and two individual switches. The "common" switch changes the state of the "sub-switches" at once, in both directions.

I want to hide the "commoN" switch and set the "Homebridge.Skip" tag on it. As it appears, this tag is only taken into account for the "top" device, but not for the sub-devices. 

It would be nice if the plugin honoured the tag also for sub-devices, as you can AFAIK only set it in Z-way at that level.

Here's the debug output with the structure:
```
  ZWayServer Got grouped device ZWayVDev_3-0 consiting of devices: +2ms
  ZWayServer ZWayVDev_zway_3-0-37 - switchBinary +2ms
  ZWayServer ZWayVDev_zway_3-0-49-4 - sensorMultilevel.Power +0ms
  ZWayServer ZWayVDev_zway_3-0-50-0 - sensorMultilevel.Electric +1ms
  ZWayServer ZWayVDev_zway_3-0-50-2 - sensorMultilevel.Electric +1ms
  ZWayServer Got grouped device ZWayVDev_3-1 consiting of devices: +2ms
  ZWayServer ZWayVDev_zway_3-1-37 - switchBinary +1ms
  ZWayServer Got grouped device ZWayVDev_3-2 consiting of devices: +1ms
  ZWayServer ZWayVDev_zway_3-2-37 - switchBinary +1ms
```

**Comment by SphtKr** [comment]
Fixed by #10
