### ISSUE TITLE
Fibaro Multiposition Motor Switch FGR211 v.2.1 can not see in Homebridge-zway

### ISSUE THREAD

**Issue by antti365** [SphtKr/homebridge-zway#66]
Hi, Homebridge-zway is latest version (0.5.0-rc0).

{"creationTime":1478890726,"creatorId":1,"deviceType":"switchBinary","h":1278853972,"hasHistory":false,"id":"ZWayVDev_zway_9-0-37","location":0,"metrics":{"icon":"switch","title":"Fibaro Switch (9.0)","level":"on"},"permanently_hidden":false,"probeType":"","tags":[],"visibility":true,"updateTime":1478891468},{"creationTime":1478890726,"creatorId":1,"deviceType":"switchMultilevel","h":1278853973,"hasHistory":false,"id":"ZWayVDev_zway_9-0-38","location":0,"metrics":{"icon":"blinds","title":"Fibaro Blind (9.0)","level":239},"permanently_hidden":false,"probeType":"motor","tags":[],"visibility":true,"updateTime":1478891468}]},"code":200,"message":"200 OK","error":null}

log:
Fri, 11 Nov 2016 19:11:15 GMT ZWayServer Fetching Z-Way devices...
Fri, 11 Nov 2016 19:11:16 GMT ZWayServer Authenticating...
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer Authenticated. Resubmitting original request...
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer Got grouped device BatteryPolling_7 consisting of devices:
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer BatteryPolling_7 - battery.Battery
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer WARN: Didn't find suitable device class!
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer Got grouped device ZWayVDev_8-0 consisting of devices:
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer ZWayVDev_zway_8-0-48-1 - sensorBinary.General purpose
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer ZWayVDev_zway_8-0-49-1 - sensorMultilevel.Temperature
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer ZWayVDev_zway_8-0-49-3 - sensorMultilevel.Luminiscence
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer ZWayVDev_zway_8-0-128 - battery.Battery
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer Got grouped device ZWayVDev_9-0 consisting of devices:
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer ZWayVDev_zway_9-0-37 - switchBinary
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer ZWayVDev_zway_9-0-38 - switchMultilevel
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer Configured Characteristic "Name" for vdev "ZWayVDev_zway_8-0-48-1"
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer Configured Characteristic "Contact Sensor State" for vdev "ZWayVDev_zway_8-0-48-1"
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer Configured Characteristic "Status Low Battery" for vdev "ZWayVDev_zway_8-0-128"
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer Adding Characteristic "Name" failed with message "Cannot add a Characteristic with the same UUID as another Characteristic in this Service: 00000023-0000-1000-8000-0026BB765291". This may be expected.
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer Found and configured Service "ContactSensor" for vdev "ZWayVDev_zway_8-0-48-1" with typeKey "sensorBinary.General purpose"
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer Configured Characteristic "Name" for vdev "ZWayVDev_zway_8-0-128"
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer Configured Characteristic "Battery Level" for vdev "ZWayVDev_zway_8-0-128"
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer Configured Characteristic "Charging State" for vdev "ZWayVDev_zway_8-0-128"
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer Configured Characteristic "Status Low Battery" for vdev "ZWayVDev_zway_8-0-128"
Fri, 11 Nov 2016 19:11:17 GMT ZWayServer Found and configured Service "BatteryService" for vdev "ZWayVDev_zway_8-0-128" with typeKey "battery.Battery"
Fri, 11 Nov 2016 19:11:18 GMT ZWayServer Configured Characteristic "Name" for vdev "ZWayVDev_zway_8-0-49-1"
Fri, 11 Nov 2016 19:11:18 GMT ZWayServer Configured Characteristic "Current Temperature" for vdev "ZWayVDev_zway_8-0-49-1"
Fri, 11 Nov 2016 19:11:18 GMT ZWayServer Found and configured Service "TemperatureSensor" for vdev "ZWayVDev_zway_8-0-49-1" with typeKey "sensorMultilevel.Temperature"
Fri, 11 Nov 2016 19:11:18 GMT ZWayServer Configured Characteristic "Name" for vdev "ZWayVDev_zway_8-0-49-3"
Fri, 11 Nov 2016 19:11:18 GMT ZWayServer Configured Characteristic "Current Ambient Light Level" for vdev "ZWayVDev_zway_8-0-49-3"
Fri, 11 Nov 2016 19:11:18 GMT ZWayServer Found and configured Service "LightSensor" for vdev "ZWayVDev_zway_8-0-49-3" with typeKey "sensorMultilevel.Luminiscence"
Fri, 11 Nov 2016 19:11:18 GMT ZWayServer Loaded services for Fibaro PIR (8.0.48.1)
Fri, 11 Nov 2016 19:11:18 GMT ZWayServer Configured Characteristic "Name" for vdev "ZWayVDev_zway_9-0-38"
Fri, 11 Nov 2016 19:11:18 GMT ZWayServer Configured Characteristic "Current Position" for vdev "ZWayVDev_zway_9-0-38"
Fri, 11 Nov 2016 19:11:18 GMT ZWayServer Configured Characteristic "Target Position" for vdev "ZWayVDev_zway_9-0-38"
Fri, 11 Nov 2016 19:11:18 GMT ZWayServer Configured Characteristic "Position State" for vdev "ZWayVDev_zway_9-0-38"
Fri, 11 Nov 2016 19:11:18 GMT ZWayServer Configured Characteristic "Hold Position" for vdev "ZWayVDev_zway_9-0-38"
Fri, 11 Nov 2016 19:11:18 GMT ZWayServer Found and configured Service "WindowCovering" for vdev "ZWayVDev_zway_9-0-38" with typeKey "switchMultilevel.blind"
Fri, 11 Nov 2016 19:11:18 GMT ZWayServer Loaded services for Fibaro Blind (9.0)
Fri, 11 Nov 2016 19:11:18 GMT EventedHTTPServer Server listening on port 51826

**Comment by SphtKr** [comment]
Well, from that it appears it configured it (correctly?) as a blind/roller shutter controller...

    Fri, 11 Nov 2016 19:11:18 GMT ZWayServer Found and configured Service "WindowCovering" for vdev "ZWayVDev_zway_9-0-38" with typeKey "switchMultilevel.blind"

Is that not correct? Does it not show up properly in Eve?

**Comment by antti365** [comment]
All right, but Eve it can not be seen...

![fullsizerender](https://cloud.githubusercontent.com/assets/6865425/20228464/f2f7d28a-a859-11e6-8eda-0afc8de34b75.jpg)

**Comment by antti365** [comment]
Hi, could you solve the problem? I never got to make sure that he appeared in Eve.

**Comment by SphtKr** [comment]
Hello, staring at this again but I'm not seeing where the problem is. Could you retrieve and attach here your [`accessories` data](https://github.com/SphtKr/homebridge-zway#getting-accessories)?

**Comment by SphtKr** [comment]
Note: Might be related to #72? General problem with WindowCovering implementation?
