### ISSUE TITLE
Deactivated Devices show up

### ISSUE THREAD

**Issue by ghulands** [SphtKr/homebridge-zway#67]
You need to skip devices with 

                "permanently_hidden": true,

So they respect the settings in the Zway UI.

**Comment by SphtKr** [comment]
So, [it does...](/SphtKr/homebridge-zway/blob/master/index.js#L224-L228)

        if(this.opt_in) isBridged = false; else isBridged = true; // Start with the initial bias
        if(vdev.permanently_hidden) isBridged = false;
        if(isTaggedInclude) isBridged = true; // Include overrides permanently_hidden
        if(isTaggedSkip) isBridged = false; // Skip overrides Include...
        if(this.opt_in && isTaggedInclude) isBridged = true; // ...unless we're in opt_in mode, where Include always wins.

Unless you've explicitly specified the tag `Homebridge.Include`...did you happen to do that?

**Comment by SphtKr** [comment]
Closing, might have been `Homebridge.Include`, might have been earlier version. Reopen if needed!
