### ISSUE TITLE
Problem with Fibaro Smoke Sensor

### ISSUE THREAD

**Issue by vsevolod-rijov** [SphtKr/homebridge-zway#75]
Hi,

I have a problem with Fibaro Smoke Sensor.
The sensor is displayed in the application, but with a message that there is no answer from device.
I'm using homebridge-zway@0.5.0-alpha4 now.

Thank you

[devices.zip](https://github.com/SphtKr/homebridge-zway/files/654994/devices.zip)

**Comment by Telefisch** [comment]
I also have the fibaro smoke-detector.
Only the roomtemperature is shown.
Is there a way to get the alarm-signals form smoke and heat also?

**Comment by vsevolod-rijov** [comment]
@Telefisch  I've already finished updating the code yourself and then saw two branches with the definition of smoke detector :)
https://github.com/SphtKr/homebridge-zway/branches
