### ISSUE TITLE
Honor "permanently_hidden" Attribute of VDev?

### ISSUE THREAD

**Issue by johannrichard** [SphtKr/homebridge-zway#8]
While Looking into #6, I realized that ZWay has an attribute known "permanently_hidden" on the VDev's that can be toggled in the UI. I was wondering whether it would not make sense to honor this, too, besides the "Homebridge.Skip" tag, and even with higher priority: After all, it's intended to hide an element more or less completely from the (ZWay) UI, so why shouldn't that apply to Homebridge, too? 

But maybe you already thought of this and discarded the idea, hence I'm happy to learn your thoughts.

```JavaScript 
ZWayServer { creationTime: 1452808859,
  creatorId: 1,
  deviceType: 'switchBinary',
  h: 1107079066,
  hasHistory: true,
  id: 'ZWayVDev_zway_3-0-37',
  location: 1,
  metrics: { icon: 'switch', title: 'Da Switch', level: 'on' },
  permanently_hidden: true,
  probeType: '',
  tags: [ 'Homebridge.Skip' ],
  visibility: true,
  updateTime: 1452839400 }
```

**Comment by SphtKr** [comment]
Heh... Okay, a few things:

1. I'd noticed that `Skip` wasn't working right and now I see why... see that line `if(this.getTagValue("Skip")...` ? That's supposed to have the vdev structure object passed as the first parameter and it's not. That needs fixing.

2. Yes, I did want to honor `permanently_hidden`, but wanted to have the ability to override it with `Homebridge.Include`, which means reversing the priority of the two tags--or at least probably so. That would let you hide something from the Z-Way interface, but make it visible to Homebridge/HomeKit, which I could definitely see coming in handy.

3. Good catch about #6, I didn't realize this didn't work for non-primary devices and it should.

I think I'm going to close pull request #7, then make some commits to your branch (I think I can do that) for #9 that will clear up all of these together.

**Comment by johannrichard** [comment]
Thansk for the comments, do as you see fit w/ adding `Homebridge.Include` – after all, it's your code. :-). 

However, you won't be able to commit to my branch since it's in my repository. What you can do, though, is create a new branch on your repo and merge my changes there, then add your changes and finally merge back to `master`.

**Comment by SphtKr** [comment]
Right.

Actually, I think the bug ("1." above) is what was preventing non-primary devices from being skipped in the first place. I overhauled that to address these and one or two other use cases. Can you switch to my `zway-permanently-hide` branch and see if that behaves as you'd expect?

**Comment by johannrichard** [comment]
:+1: The `zway-permanently-hide` branch behaves as expected.

**Comment by SphtKr** [comment]
Superseded by #10
