### ISSUE TITLE
Smoke sensor not reporting triggers

### ISSUE THREAD

**Issue by Telefisch** [SphtKr/homebridge-zway#80]
I think I dont understand this all...
I installed the package like shown under Quickstart an I can see the fibaro smoke sensors temperature.
I could not get the state of smoke-alarm or temp-alarm.
What do I have to do additionally?
Where do I use the Tags?

Is there any howto?
thanks

**Comment by SphtKr** [comment]
Hey there, so, when you say you see the smoke sensors and temperature, where do you see them? The console output is all only for logging or debugging. You'll have to pair Homebridge with your iPhone/iPad and look at states there. Look at [this section of the Homebridge README](https://github.com/nfarina/homebridge/#adding-homebridge-to-ios), it may be what you're looking for. If not, give me some more info about what you do and don't see and where you see it.

**Comment by Telefisch** [comment]
FYI, I have some other plugins running without problems, so Homebridge itself is working fine.

**Comment by SphtKr** [comment]
I will have to go back and test mine. I haven't actually caused my smoke alarm (I have a Fibaro model) to be triggered, I have simulated it with software devices. Perhaps it actually doesn't work as I expected.

Note also though, that Apple _just_ added support for notifications from smoke sensors in 10.2. Previous to that, you would only notice that a smoke alarm was triggered if you were looking at the Home app at that time (besides the screeching noise of course). In 10.2, it will send you a notification...but you also may have to enable it in the Home app (long-press on device and select "Details" and then "Status and Notifications") if you already had the device in your network before the 10.2 upgrade...unsure about that.

**Comment by Telefisch** [comment]
I also have the fibaro device. If I can help with additional information, your welcome.

**Comment by SphtKr** [comment]
Should be fixed in 0.5.0-rc1 --update and check please!

**Comment by Telefisch** [comment]
Seems to be better...

**Comment by SphtKr** [comment]
Yes--there's not a heat sensor exactly in HomeKit, so if I bridge it I have to be creative. Haven't figured that out yet.

**Comment by SphtKr** [comment]
Closing with this ticket as smoke detectors are now fixed--the heat-infrared issue is moved to another issue number.
