### ISSUE TITLE
Can anyone confirm the Aeotec by Aeon Labs ZW090 Z Stick works with the plugin?

### ISSUE THREAD

**Issue by ehusar** [SphtKr/homebridge-zway#85]
I am looking to buy a Aeotec by Aeon Labs ZW090 Z Stick. I am looking for a confirmation the home bridge-zway plugin will work for z-wave devices and the Z Stick.

Thank you.

**Comment by SphtKr** [comment]
I would suggest "no", but I think the question is a little incorrect--the question you should ask is whether the Aeon Labs stick will work with Z-Way, which is a software product from [Z-Wave.me](http://www.z-wave.me/index.php?id=22). This plugin only talks to the Z-Way server software, which is abstracted from the actual radio transceiver hardware. It may actually be the case that Z-Way software will work with the Aeon Labs stick, but if so you'd still have to buy the license for Z-Way Server in that case.

On the off chance you're looking at the Aeon Labs stick because you don't want to use a RPi, note that [Z-Wave.me does sell a USB stick also](http://www.z-wave.me/index.php?id=28), which is usually sold with a license to the Z-Way software (which I think you can even run on Windows...but not Mac), and which should work with this plugin.

**Comment by ehusar** [comment]
Are you sure about that?  The Z Stick is a licensed z-wave product.  There is a lot of positive feedback on Amazon about people using this stick alone with an RPi to control z-wave devices with Domoticz, HomeAssistance, and just about every other home automation software package.  

Wait, that is because this plugin is for z-way not generic z-wave devices?  Am I confused? I very well maybe.

> The Aeon labs z-stick is a Z-Wave USB dongle. When attached to a host processor, it becomes a Z-Wave communication device, which exposes the zensys api (serialapi) through integrated USB. This device is meant primarily to allow a host processor to control up to 232 Z-Wave devices using the Z-Wave technology protocol all the while simplifying Z-Wave network installation. Furthermore, the Aeon labs z-stick is easily upgradeable by the enduser such that the latest Z-Wave protocols and commands are always available. It can be upgraded in field via its USB port which also serves as a charging port for its internal battery.

**Comment by ehusar** [comment]
Isn't the Z Stick the same as the UZB?

**Comment by SphtKr** [comment]
> Wait, that is because this plugin is for z-way not generic z-wave devices? Am I confused? I very well maybe.

Exactly.

> Isn't the Z Stick the same as the UZB?

Not sure, and depends on how "exactly" you mean...but either way, yes, the first quote above is the point. It may very well be that they're the same enough that the Z-Way software works with the Aeon Labs stick...but for this plugin to work, you'd have to have the Z-Way Server software.

**Comment by ehusar** [comment]
Okay, I am buying one so I will report back if it works with your plugin.

Thanks1

**Comment by gijoecool** [comment]
@ehusar I have a Z Stick on a separate Raspberry Pi from my RaZberry and I like a lot. However, I am running openHAB on that one (not Z-Way-Server). It could be beneficial to look into other platforms...

**Comment by ehusar** [comment]
Thanks gijoecool.   I'm looking into OpenHAB. Just to confirm the Z Stick does the same thing as the Razberry.  It is a ZWave server, right?

**Comment by gijoecool** [comment]
Yep. The only issue I've had is lack of z-wave security device support in openHAB. (This should be better now but I haven't had time to set it up.)

The device itself works flawlessly though. And it's a lot easier to include/exclude devices than with the RaZberry.

**Comment by ehusar** [comment]
I picked one up on Amazon last night so I'll test it out when it arrives on Friday.   I also picked up a Z-Wave dimmable light switch from Linear to use as a test.  I'm hoping the dimmer works. As long as the Z Stick works well with Homebridge, a Z-Wave plugin, and The Apple Home app I'll be set to start integrating more Z-Wave devices.

**Comment by petonic** [comment]
So, I'm in suspense. Did the Aeonlabs zwave usb-stick work?

**Comment by jasmas** [comment]
@ehusar did it work?

**Comment by laibulle** [comment]
Does not work on my side

```
[2018-09-02 01:32:27.850] [D] [zway] Initialization done
[2018-09-02 01:32:27.850] [D] [zway] Job 0x07 (Get controller info and supported function classes): success
[2018-09-02 01:32:27.850] [C] [zway] Device is not compatible. Terminating...
[2018-09-02 01:32:27.850] [I] [zway] Removing job: Get controller info and supported function classes
[2018-09-02 01:32:27.869] [D] [zway] Worker thread exit point
[2018-09-02 01:32:27.869] [D] [zway] Worker thread successfully finished
[2018-09-02 01:32:27.898] [E] [zway] SaveData will not save data since it wasn't loaded. This is to prevent data loss.
[2018-09-02 01:32:27.899] [I] [core] Error: Bad data - communication failed
[2018-09-02 01:32:27.899] [I] [core] Tried 5 times without success. Stopping tries.
[2018-09-02 01:32:27.900] [I] [core] Notification: critical (z-wave): Cannot start Z-Wave binding: Error: Bad data - communication failed
```
