### ISSUE TITLE
Information to get started

### ISSUE THREAD

**Issue by flippamike** [SphtKr/homebridge-zway#91]
Hi People, 

I hope someone can help me with some startup information. I am running homebride for a while now and its working fine. I just bought a z-wave device that i would like to add. And i am looking for confirmation that i am on the right track. 

I am thinking to install the Z-wave server (http://razberry.z-wave.me/index.php?id=24) on the same Pi that is  running homebrdige and extending the board with the Razberry module (http://razberry.z-wave.me/index.php?id=9) will this be enough to manage z-wave devices? Or can i better take an other route ?

Thanks for the help,

Mike

**Comment by Fingerz** [comment]
The approach you describe is exactly the approach that most of us are taking (ZWay + Razberry + Homebridge + Homebridge-zway all running on the same RasperryPi 2/3). I'm managing 20+ Z-wave devices (switches, dimmers, door locks, motorized blinds, etc.) using this method with good success.

**Comment by flippamike** [comment]
Thanks @Fingerz for the feedback. When i look online for the module i see different sites claiming to have version 2 of the module. I see 2 different versions and sizes  

The big one : https://en.robbshop.nl/media/catalog/product/cache/1/image/9cf863cbec73c5577e00b91be2fdb6b0/z/m/zme_eraz_2.jpg

And a smaller one :  https://www.robbshop.nl/media/catalog/product/cache/2/image/9cf863cbec73c5577e00b91be2fdb6b0/z/m/zmeeraz-2.png

Is the last one the one you need to buy ?

**Comment by SphtKr** [comment]
I have seen the v2 and looked into it, the only difference I've seen is that the v2 is supposed to have a larger antenna, supposedly helping with range. I have had the odd problem pairing devices with my v1 (some devices like the Danalock wouldn't pair unless I brought the RPi within line-of-sight), so a better antenna might be worth getting, but I haven't tried it myself.

Be advised with both versions (I'm pretty sure) there is some juggling you have to do with the Bluetooth hardware if you use a Pi 3--the RaZBerry uses the same UART that the new Pi's Bluetooth uses, so you have to either disable bluetooth or switch it to the software-based UART...Google will explain.

FWIW, I'm running Homebridge on a Mac and communicating to Z-Way running on a Pi 3, so it is possible to do that too. But yes you should be able to run both on the same device.
