### ISSUE TITLE
Z-Wave USB tick Gen 3

### ISSUE THREAD

**Issue by livefeed** [SphtKr/homebridge-zway#97]
Hi, 

Will this work with a Z-Wave USB tick Gen 3?

**Comment by moosebert** [comment]
Nothing to do with this module, but rather the Z-Way software.  Ask in the Z-Wave.me forums.

**Comment by SphtKr** [comment]
Yeah, I think the answer is yes, but it's truly a matter of whether it works with Z-Way itself, so you'll have to ask them. If you can get Z-Way to work with it, Homebridge-ZWay will work with Z-Way.
